"use client";

// components/quotation/QuotationSendDialog.tsx
//
// Deliver a `sent` quotation to the customer (Phase 4, spec I4), over email,
// over the tenant's own WhatsApp sender, or both.
//
// THE SENDER IS RESOLVED SERVER-SIDE, AND THIS DIALOG MUST NOT TRY TO GUESS IT.
// A seller holding only `quotations` cannot call `GET /omnichannels/accounts`
// (that route needs `omnichannel:use` or `omnichannel:setup`, which Staff does
// not hold), so enumerating WhatsApp accounts the way the template screens do
// with `useSelectedWaAccount` would 403 for exactly the person who sends
// quotations all day. The server picks the account; when a tenant has MORE
// THAN ONE active WhatsApp account it refuses to guess and answers 400 asking
// for an explicit sender.
//
// That refusal needs an ANSWER, though, and it did not have one: no control on
// this page could produce an `account_id`, so WhatsApp delivery was
// permanently impossible for any tenant with two numbers (dev's company
// 6fb093c6 has exactly that shape today). `GET /quotations/whatsapp-senders`
// is the narrow read that closes it - `quotations`-gated, id + label + number
// and no credentials - and the picker below appears ONLY when it returns more
// than one row, so the single-account tenant still sees nothing extra and the
// server still owns the decision.
//
// The PDF is generated by the CALLER (the form, or the list row action) and
// handed over as a promise, because the hidden <QuotationPdfDocument/> node
// lives in those screens and the bytes cannot be recovered after the request.
// The upload happens inside `POST /send`: an existing `pdf_file_id` whose
// SHA-256 still matches is reused rather than uploaded twice (A14).

import { useCallback, useEffect, useRef, useState } from "react";
import { Dialog, DialogContent, Chip } from "@mui/material";
import { Copy, Mail, MessageCircle, Send, X } from "lucide-react";
import { format } from "date-fns";
import { AppButton } from "@/components/ui/app-button";
import { AppInput } from "@/components/ui/app-input";
import { notify } from "@/lib/notifications";
import { useAuth } from "@/lib/context/AuthContext";
import {
  fetchQuotationDeliveries,
  fetchQuotationWhatsappSenders,
  sendQuotation,
} from "@/lib/api/quotations";
import { AppSelect } from "@/components/ui/app-select";
import { publicQuotationUrl } from "@/lib/api/quotations-public";
import { mapQuotationException } from "@/lib/utils/quotation-errors";
import type {
  Quotation,
  QuotationDelivery,
  QuotationSendChannel,
  QuotationWhatsappSender,
} from "@/lib/types/Quotation";

interface QuotationSendDialogProps {
  open: boolean;
  onClose: () => void;
  quotation: Quotation | null;
  /** The customer's email as the quotation knows it; blank disables Email. */
  contactEmail?: string | null;
  /** The customer's phone; editable, because a WhatsApp number often differs. */
  contactPhone?: string | null;
  /**
   * Renders the hidden PDF template for THIS quotation and returns the blob.
   * Returning null means the render failed and the caller has already said so.
   */
  onGeneratePdf: (quotation: Quotation) => Promise<Blob | null>;
  /** Called with the server's response after a successful send, so the caller
   *  can refresh its row (`pdf_url`, `deliveries_count`, `acceptance_url`). */
  onSent?: (deliveries: QuotationDelivery[], acceptanceUrl: string | null) => void;
}

const CHANNELS: { value: QuotationSendChannel; label: string; icon: React.ReactNode }[] = [
  { value: "email", label: "Email", icon: <Mail size={16} /> },
  { value: "whatsapp", label: "WhatsApp", icon: <MessageCircle size={16} /> },
  { value: "both", label: "Keduanya", icon: <Send size={16} /> },
];

const DELIVERY_STATUS_META: Record<
  QuotationDelivery["status"],
  { label: string; color: "default" | "success" | "error" | "warning" }
> = {
  pending: { label: "Diproses", color: "warning" },
  sent: { label: "Terkirim", color: "success" },
  failed: { label: "Gagal", color: "error" },
  // `skipped` is a real, expected outcome - no contact email, or a
  // non-production WhatsApp send with QUOTATION_WA_SANDBOX_TO unset (A9) -
  // so it is labelled as a decision, not painted as a failure.
  skipped: { label: "Dilewati", color: "default" },
};

function safeDateTime(value?: string | null): string {
  if (!value) return "-";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "-" : format(date, "dd MMM yyyy HH:mm");
}

function DeliveryRows({ rows }: { rows: QuotationDelivery[] }) {
  if (rows.length === 0) return null;
  return (
    <ul className="mt-2 space-y-2">
      {rows.map((row) => {
        const meta = DELIVERY_STATUS_META[row.status] ?? DELIVERY_STATUS_META.pending;
        return (
          <li key={row.id} className="rounded-md border border-gray-200 px-3 py-2 text-sm">
            <div className="flex items-center justify-between gap-2">
              <span className="font-medium text-gray-800">
                {row.channel === "email" ? "Email" : "WhatsApp"}
                {row.recipient ? ` - ${row.recipient}` : ""}
              </span>
              <Chip label={meta.label} color={meta.color} size="small" />
            </div>
            <p className="mt-0.5 text-xs text-gray-500">
              {row.sent_at ? safeDateTime(row.sent_at) : safeDateTime(row.created_at)}
            </p>
            {row.error_message && (
              <p className="mt-1 text-xs text-red-600">{row.error_message}</p>
            )}
          </li>
        );
      })}
    </ul>
  );
}

export default function QuotationSendDialog({
  open,
  onClose,
  quotation,
  contactEmail,
  contactPhone,
  onGeneratePdf,
  onSent,
}: QuotationSendDialogProps) {
  const { getToken } = useAuth();

  const [channel, setChannel] = useState<QuotationSendChannel>("email");
  const [phone, setPhone] = useState("");
  const [sending, setSending] = useState(false);
  const [history, setHistory] = useState<QuotationDelivery[]>([]);
  const [result, setResult] = useState<QuotationDelivery[] | null>(null);
  const [failure, setFailure] = useState<string | null>(null);
  const [acceptanceUrl, setAcceptanceUrl] = useState<string | null>(null);
  const [senders, setSenders] = useState<QuotationWhatsappSender[]>([]);
  const [senderId, setSenderId] = useState("");
  const sendersLoadedRef = useRef(false);

  const hasEmail = !!contactEmail?.trim();
  const wantsWhatsapp = channel !== "email";

  // Reset on every open: a dialog that remembers the previous quotation's
  // channel, phone and result is a dialog that sends the wrong thing.
  useEffect(() => {
    if (!open) return;
    setChannel(hasEmail ? "email" : "whatsapp");
    setPhone(contactPhone?.trim() ?? "");
    setResult(null);
    setFailure(null);
    setSending(false);
    setSenderId("");
    setAcceptanceUrl(
      quotation?.acceptance_url ?? publicQuotationUrl(quotation?.public_code)
    );
  }, [open, hasEmail, contactPhone, quotation?.acceptance_url, quotation?.public_code]);

  // Lazily, and only for a channel that can actually use it: a tenant that
  // never sends on WhatsApp should not pay a request for a picker it will
  // never see. A failure here is silent by design - the server still resolves
  // the sender on its own for the single-account case, which is most tenants,
  // and a red toast would fire for every one of them.
  useEffect(() => {
    // Once per mount, not once per channel toggle: the list is tenant-level
    // and a seller flipping Email/WhatsApp/Keduanya must not re-request it.
    if (!open || !wantsWhatsapp || sendersLoadedRef.current) return;
    sendersLoadedRef.current = true;
    let cancelled = false;
    void (async () => {
      try {
        const rows = await fetchQuotationWhatsappSenders(await getToken());
        if (!cancelled) setSenders(rows);
      } catch {
        if (!cancelled) setSenders([]);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [open, wantsWhatsapp, getToken]);

  const loadHistory = useCallback(async () => {
    if (!open || !quotation?.id) return;
    try {
      const token = await getToken();
      setHistory(await fetchQuotationDeliveries(token, quotation.id));
    } catch {
      // History is context, not an action. A failure here stays silent rather
      // than putting a red toast in front of a send the seller came to do.
      setHistory([]);
    }
  }, [getToken, open, quotation?.id]);

  useEffect(() => {
    void loadHistory();
  }, [loadHistory]);

  const handleSend = async () => {
    if (!quotation) return;
    if (channel !== "whatsapp" && !hasEmail) {
      setFailure("Kontak ini tidak punya alamat email. Pilih WhatsApp, atau lengkapi email kontaknya.");
      return;
    }
    setSending(true);
    setFailure(null);
    try {
      const pdf = await onGeneratePdf(quotation);
      if (!pdf) {
        setFailure("PDF gagal dibuat, jadi tidak ada yang dikirim. Coba lagi.");
        return;
      }
      const token = await getToken();
      const response = await sendQuotation(token, quotation.id, {
        channel,
        pdf,
        // Named server-side too, but the local download and the upload should
        // spell the file the same way.
        filename: `quotation-${quotation.quotation_number}.pdf`,
        toPhone: channel === "email" ? null : phone,
        // Only ever sent when the seller actually chose one. Left empty the
        // server resolves it, and refuses only when there is a real ambiguity.
        accountId: wantsWhatsapp && senderId ? senderId : null,
      });
      setResult(response.deliveries ?? []);
      setAcceptanceUrl(response.acceptance_url ?? acceptanceUrl);
      onSent?.(response.deliveries ?? [], response.acceptance_url ?? null);
      void loadHistory();

      const failedRows = (response.deliveries ?? []).filter((d) => d.status === "failed");
      if (failedRows.length > 0) {
        // A partial failure gets the SAME red panel a refusal does, beside the
        // channel picker. With `channel=both` the WhatsApp half can fail while
        // the email goes out, and a green toast plus one green row was how a
        // seller came to believe a message had been delivered that never was.
        setFailure(
          failedRows
            .map(
              (row) =>
                `${row.channel === "email" ? "Email" : "WhatsApp"}: ${
                  row.error_message || "pengiriman gagal"
                }`
            )
            .join(" ")
        );
        notify.warning("Sebagian pengiriman gagal", {
          description: "Lihat rincian di dialog ini.",
        });
      } else {
        notify.success("Quotation dikirim", {
          description: `Quotation ${quotation.quotation_number} diteruskan ke pelanggan.`,
        });
      }
    } catch (error: any) {
      const mapped = mapQuotationException(error);
      // Every refusal the server can give here is actionable, so it is shown
      // IN the dialog beside the picker rather than only as a toast: the
      // template-not-approved case in particular tells the tenant to get their
      // `quotation_send` template through Meta review, which is not a retry.
      setFailure(mapped.message);
      // A TIMEOUT OR A DROPPED CONNECTION IS NOT PROOF THAT NOTHING WAS SENT.
      // `TimeoutMiddleware` answers 408 without stopping the endpoint, which
      // keeps running headless, so the upload, the email and the delivery row
      // can all complete after the client has given up. Reload the history
      // before the seller decides to press Kirim again - only the PDF upload
      // is de-duplicated, so a blind retry re-sends the message.
      // `QuotationApiError.status` is absent entirely for a client-side
      // timeout or a dropped connection, which is exactly the case that needs
      // the reload most.
      const httpStatus = (error as { status?: number } | null)?.status;
      if (!httpStatus || httpStatus === 408 || httpStatus >= 500) {
        void loadHistory();
      }
    } finally {
      setSending(false);
    }
  };

  const copyLink = () => {
    if (!acceptanceUrl) return;
    void navigator.clipboard.writeText(acceptanceUrl);
    notify.success("Tautan disalin", {
      description: "Tautan persetujuan pelanggan disalin ke clipboard.",
    });
  };

  const recipientLine =
    channel === "whatsapp"
      ? phone.trim() || "nomor WhatsApp kontak"
      : channel === "email"
        ? contactEmail?.trim() || "-"
        : `${contactEmail?.trim() || "-"} dan ${phone.trim() || "nomor WhatsApp kontak"}`;

  return (
    <Dialog open={open} onClose={sending ? undefined : onClose} maxWidth="sm" fullWidth>
      <DialogContent className="p-6">
        <div className="mb-4 flex items-start justify-between gap-4">
          <div>
            <h2 className="text-lg font-bold text-gray-900">Kirim ke pelanggan</h2>
            <p className="text-sm text-gray-500">
              {quotation?.quotation_number
                ? `Quotation ${quotation.quotation_number}`
                : "Quotation"}
            </p>
          </div>
          <button
            type="button"
            aria-label="Tutup"
            onClick={onClose}
            disabled={sending}
            className="rounded-md p-1 text-gray-400 hover:bg-gray-100 disabled:opacity-40"
          >
            <X size={18} />
          </button>
        </div>

        <fieldset className="mb-4">
          <legend className="mb-2 text-sm font-medium text-gray-700">Kanal pengiriman</legend>
          <div className="flex flex-wrap gap-2">
            {CHANNELS.map((option) => {
              const disabled = option.value !== "whatsapp" && !hasEmail;
              const selected = channel === option.value;
              return (
                <button
                  key={option.value}
                  type="button"
                  disabled={disabled || sending}
                  onClick={() => setChannel(option.value)}
                  aria-pressed={selected}
                  className={`flex items-center gap-2 rounded-full border px-4 py-2 text-sm transition-colors ${
                    selected
                      ? "border-indigo-500 bg-indigo-50 text-indigo-700"
                      : "border-gray-300 text-gray-600 hover:bg-gray-50"
                  } disabled:cursor-not-allowed disabled:opacity-40`}
                >
                  {option.icon}
                  {option.label}
                </button>
              );
            })}
          </div>
          {!hasEmail && (
            <p className="mt-2 text-xs text-amber-700">
              Kontak ini belum punya alamat email, jadi hanya WhatsApp yang tersedia.
            </p>
          )}
        </fieldset>

        {wantsWhatsapp && senders.length > 1 && (
          <div className="mb-4">
            <AppSelect
              isBgWhite
              fullWidth
              label="Nomor pengirim WhatsApp"
              // Nothing is pre-selected on purpose: which department's number
              // a quotation goes out from is a DECISION, and the server
              // refuses to guess it. Picking one for the seller here would
              // just move the guess into the browser.
              placeholder="Pilih nomor pengirim"
              value={senderId}
              options={senders.map((sender) => ({
                value: sender.id,
                label: `${sender.display_name} - ${sender.channel_identifier}${
                  sender.branch ? ` (${sender.branch})` : ""
                }`,
              }))}
              onChange={(e) => setSenderId(String(e.target.value))}
              helperText="Workspace ini punya lebih dari satu nomor WhatsApp aktif, jadi pengirimnya harus dipilih."
            />
          </div>
        )}

        {channel !== "email" && (
          <div className="mb-4">
            <AppInput
              isBgWhite
              label="Nomor WhatsApp"
              placeholder="mis. +628123456789"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              disabled={sending}
              helperText={
                senders.length > 1
                  ? "Kosongkan untuk memakai nomor kontak. Nomor pengirim dipilih di atas."
                  : "Kosongkan untuk memakai nomor kontak. Pengirimnya ditentukan server dari akun WhatsApp workspace."
              }
            />
          </div>
        )}

        <p className="mb-4 rounded-md bg-gray-50 px-3 py-2 text-sm text-gray-600">
          Akan dikirim ke: <span className="font-medium text-gray-900">{recipientLine}</span>
        </p>

        {acceptanceUrl && (
          <div className="mb-4 rounded-md border border-indigo-100 bg-indigo-50 px-3 py-2">
            <p className="text-xs font-medium text-indigo-900">Tautan persetujuan pelanggan</p>
            <div className="mt-1 flex items-center gap-2">
              <code className="min-w-0 flex-1 truncate text-xs text-indigo-800">{acceptanceUrl}</code>
              <button
                type="button"
                onClick={copyLink}
                className="flex shrink-0 items-center gap-1 text-xs font-medium text-indigo-700 hover:underline"
              >
                <Copy size={14} />
                Salin
              </button>
            </div>
          </div>
        )}

        {failure && (
          <p className="mb-4 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
            {failure}
          </p>
        )}

        {result && (
          <div className="mb-4">
            <p className="text-sm font-medium text-gray-800">Hasil pengiriman</p>
            <DeliveryRows rows={result} />
          </div>
        )}

        {!result && history.length > 0 && (
          <div className="mb-4">
            <p className="text-sm font-medium text-gray-800">Pengiriman sebelumnya</p>
            <DeliveryRows rows={history} />
          </div>
        )}

        {!result && history.length === 0 && (
          <p className="mb-4 text-sm text-gray-500">Belum ada pengiriman tercatat.</p>
        )}

        <div className="flex justify-end gap-2">
          <AppButton variantStyle="outline" color="gray" onClick={onClose} disabled={sending}>
            Tutup
          </AppButton>
          <AppButton onClick={handleSend} isLoading={sending} disabled={sending || !quotation}>
            <Send size={16} className="mr-2" />
            {result ? "Kirim ulang" : "Kirim"}
          </AppButton>
        </div>
      </DialogContent>
    </Dialog>
  );
}
