/**
 * SmartSales Web Widget - embeddable "Support Assistant" chat widget.
 *
 * Deliberately vanilla TypeScript (no React/Preact) rendered into a Shadow
 * DOM: this script runs on a THIRD-PARTY tenant website, not inside
 * supercontact-web itself, so it must not bloat the host page's bundle or
 * collide with whatever framework/CSS that page already uses. See plans/
 * for the full architecture rationale.
 *
 * Reads its own <script data-widget-key="..." data-api-url="..."> tag via
 * document.currentScript - both attributes are generated by the tenant's
 * Settings > Web Widget page (WebWidgetEmbedGuide.tsx) at copy time, so
 * this bundle itself never hardcodes an environment.
 *
 * UI/UX: a small view state machine (home <-> chat). The RENDER layer was
 * redesigned for the Support Assistant concept (home screen, quick-action
 * cards, human handoff, presence, privacy footer, mobile full-screen); the
 * transport/resilience layer (config fetch, localStorage session, REST
 * /start + /messages with idempotency + optimistic send/retry, receive-only
 * WS with backoff+jitter reconnect, ping/pong, dedupe, resync, 401 purge,
 * 1008 stop, direction inversion, unread badge, title flash, a11y, shadow
 * isolation) is preserved verbatim.
 */

interface QuickAction {
  id: string;
  label: string;
  description?: string | null;
  icon?: string | null;
  target_queue_id?: string | null;
  prefill?: string | null;
}

interface WidgetPresence {
  online: boolean;
  count: number;
  avatars: string[];
}

interface WidgetConfig {
  title: string;
  greeting_message: string;
  brand_color: string;
  is_widget_enabled: boolean;
  is_within_business_hours: boolean;
  offline_message?: string | null;

  // Support Assistant concept fields (added to GET /public/widget/config/{key}).
  bot_name?: string | null;
  bot_avatar_url?: string | null;
  home_headline?: string | null;
  home_subtext?: string | null;
  show_home_screen?: boolean;
  quick_actions?: QuickAction[] | null;
  response_time_label?: string | null;
  show_presence?: boolean;
  enable_human_handoff?: boolean;
  handoff_label?: string | null;
  handoff_queue_id?: string | null;
  privacy_footer_text?: string | null;
  privacy_url?: string | null;
  presence?: WidgetPresence | null;

  // AI Answer Bot (Phase 7B) - the PUBLIC subset of the tenant's answer-bot
  // config (get_public_config omits answer_bot_min_confidence, which is
  // server-side only). In 7B.1 the bot's reply arrives as a normal OUTBOUND
  // message and renders as a team bubble, so these fields need no new render
  // branch today - they're declared so a later 7B.2 rich card can consume them.
  answer_bot_enabled?: boolean;
  answer_bot_max_articles?: number;
  answer_bot_use_llm?: boolean;
  answer_bot_intro_text?: string | null;
  answer_bot_no_answer_text?: string | null;

  // i18n (POLISH sprint): the public config endpoint does NOT currently
  // return these, so today they're always undefined and the widget falls
  // back to the data-locale attribute (default "id"). Kept optional so that
  // IF the backend ever adds a `locale`/`strings` field to get_public_config
  // it's picked up with zero further frontend change - see resolveStrings().
  locale?: "id" | "en" | string | null;
  strings?: Partial<WidgetStrings> | null;
}

// All visitor-facing chrome strings. Everything the widget renders in the
// UI flows through one of these keys so the bundle can ship more than one
// language pack without touching the backend.
interface WidgetStrings {
  offline: string;
  offlineShort: string;
  online: string;
  disconnected: string;
  yourName: string;
  yourEmail: string;
  typeMessage: string;
  send: string;
  openChat: string;
  closeChat: string;
  failedRetry: string;
  newMessage: string;
  downloadAttachment: string;
  attachment: string;
  // Support Assistant chrome:
  greetingHi: string;
  homeHeadline: string;
  homeSubtext: string;
  needMoreHelp: string;
  teamHere: string;
  handoffDefault: string;
  connectedAgent: string;
  talkToHuman: string;
  helpWithPrefix: string;
  startOver: string;
  back: string;
  menu: string;
}

const STRINGS_EN: WidgetStrings = {
  offline: "We're currently offline",
  offlineShort: "Offline",
  online: "Online",
  disconnected: "Disconnected — refresh to reconnect",
  yourName: "Your name",
  yourEmail: "Your email (optional)",
  typeMessage: "Type a message...",
  send: "Send",
  openChat: "Open chat",
  closeChat: "Close chat",
  failedRetry: "Failed — tap to retry",
  newMessage: "New message",
  downloadAttachment: "Download attachment",
  attachment: "attachment",
  greetingHi: "Hi there! 👋",
  homeHeadline: "How can we help?",
  homeSubtext: "Choose an option below or send us a message.",
  needMoreHelp: "Need more help?",
  teamHere: "Our team is here for you",
  handoffDefault: "Talk to a human",
  connectedAgent: "You're connected with an agent",
  talkToHuman: "I'd like to talk to a human",
  helpWithPrefix: "I'd like help with: ",
  startOver: "Start over",
  back: "Back",
  menu: "More options",
};

const STRINGS_ID: WidgetStrings = {
  offline: "Kami sedang offline",
  offlineShort: "Offline",
  online: "Online",
  disconnected: "Koneksi terputus — muat ulang untuk menyambung kembali",
  yourName: "Nama Anda",
  yourEmail: "Email Anda (opsional)",
  typeMessage: "Ketik pesan...",
  send: "Kirim",
  openChat: "Buka obrolan",
  closeChat: "Tutup obrolan",
  failedRetry: "Gagal — ketuk untuk mencoba lagi",
  newMessage: "Pesan baru",
  downloadAttachment: "Unduh lampiran",
  attachment: "lampiran",
  greetingHi: "Halo! 👋",
  homeHeadline: "Ada yang bisa kami bantu?",
  homeSubtext: "Pilih opsi di bawah atau kirim pesan kepada kami.",
  needMoreHelp: "Butuh bantuan lain?",
  teamHere: "Tim kami siap membantu Anda",
  handoffDefault: "Bicara dengan agen",
  connectedAgent: "Anda terhubung dengan agen",
  talkToHuman: "Saya ingin berbicara dengan agen",
  helpWithPrefix: "Saya butuh bantuan tentang: ",
  startOver: "Mulai ulang",
  back: "Kembali",
  menu: "Opsi lainnya",
};

// Base pack selected by locale (default Indonesian - the product's tenants
// are Indonesian), then merged with any per-string overrides (only ever
// present if the backend later supplies config.strings).
function resolveStrings(
  locale: string | null | undefined,
  overrides?: Partial<WidgetStrings> | null,
): WidgetStrings {
  const base = locale === "en" ? STRINGS_EN : STRINGS_ID;
  const merged: WidgetStrings = { ...base };
  if (overrides) {
    for (const k in overrides) {
      const v = (overrides as Record<string, unknown>)[k];
      if (typeof v === "string" && v.trim()) (merged as unknown as Record<string, string>)[k] = v;
    }
  }
  return merged;
}

interface StoredSession {
  visitor_token: string;
  conversation_id: string;
}

interface WidgetAttachment {
  filename?: string | null;
  content_type?: string | null;
  media_url: string;
  is_inline?: boolean;
}

interface WidgetMessage {
  id?: string;
  direction: "inbound" | "outbound";
  content: string;
  sent_at?: string;
  media_url?: string | null;
  attachments?: WidgetAttachment[];
  // Client-only bookkeeping (never sent to the server):
  client_message_id?: string; // idempotency key so a retry can't double-post
  status?: "sending" | "sent" | "failed";
  // Routing context captured at conversation start so a retry re-POSTs the
  // SAME /start payload (queue + originating quick-action). Anonymous start:
  // no visitor_name/visitor_email captured up-front anymore.
  startCtx?: { target_queue_id?: string | null; action_id?: string | null };
}

// Server-shaped message as returned by GET /public/widget/conversation and
// the WS "message" frame. NOTE the direction inversion vs the widget UI:
// the backend is company-centric (visitor = "inbound", agent = "outbound"),
// but the visitor-facing bubble is visitor-centric (their own message =
// "outbound"/right, an agent reply = "inbound"/left). fromServer() flips it.
interface ServerMessage {
  id?: string;
  direction?: string;
  content?: string;
  sent_at?: string;
  media_url?: string | null;
  attachments?: WidgetAttachment[] | null;
}

// ---- Inline icon set (static, trusted SVG - no user data interpolated) ----
const IC_QUESTION =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8z"/></svg>';
const IC_DOLLAR =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>';
const IC_PACKAGE =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="16.5" y1="9.4" x2="7.5" y2="4.21"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>';
const IC_PERSON =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>';
const IC_SPARK =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9z"/></svg>';
const IC_CHEVRON =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>';
const IC_ROBOT =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="8" width="16" height="12" rx="2"/><path d="M12 8V5"/><circle cx="12" cy="4" r="1" fill="currentColor" stroke="none"/><circle cx="9" cy="13" r="1" fill="currentColor" stroke="none"/><circle cx="15" cy="13" r="1" fill="currentColor" stroke="none"/><path d="M9.5 16.5h5"/></svg>';
const IC_SHIELD =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>';
const IC_SEND =
  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>';

// Map a quick-action's free-form `icon` string to a themed tile + glyph.
// Supports at least: question/chat, quote/dollar, order/package, sales/person,
// and a sensible sparkle default.
function iconMeta(icon?: string | null): { svg: string; bg: string; fg: string } {
  const k = (icon || "").toLowerCase();
  const has = (...xs: string[]) => xs.some((x) => k.includes(x));
  if (has("quote", "dollar", "price", "pricing", "billing", "payment", "cost", "plan", "money"))
    return { bg: "#ECFDF3", fg: "#16A34A", svg: IC_DOLLAR };
  if (has("order", "package", "box", "ship", "track", "deliver", "product", "return", "refund"))
    return { bg: "#FEF6E7", fg: "#D97706", svg: IC_PACKAGE };
  if (has("sales", "person", "people", "contact", "agent", "human", "talk", "call", "demo", "team"))
    return { bg: "#F3EEFF", fg: "#7C3AED", svg: IC_PERSON };
  if (has("question", "help", "chat", "support", "faq", "ask", "message", "info", "how"))
    return { bg: "#EFF4FF", fg: "#3B6EF6", svg: IC_QUESTION };
  return { bg: "#EEF2F7", fg: "#475569", svg: IC_SPARK };
}

// Darken a #RRGGBB hex toward black by `amount` (0..1). Used to derive the
// header's gradient top stop from the tenant brand color. Invalid input is
// returned unchanged so styling never throws on a malformed brand_color.
function darken(hex: string, amount: number): string {
  const m = /^#?([0-9a-f]{6})$/i.exec((hex || "").trim());
  if (!m) return hex;
  const n = parseInt(m[1], 16);
  const r = Math.max(0, Math.round(((n >> 16) & 255) * (1 - amount)));
  const g = Math.max(0, Math.round(((n >> 8) & 255) * (1 - amount)));
  const b = Math.max(0, Math.round((n & 255) * (1 - amount)));
  return `#${((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1)}`;
}

// Build a span wrapping a static (trusted) SVG string.
function svgEl(svg: string, cls?: string): HTMLSpanElement {
  const span = document.createElement("span");
  span.innerHTML = svg;
  if (cls) span.className = cls;
  return span;
}

(function () {
  const currentScript = document.currentScript as HTMLScriptElement | null;
  if (!currentScript) return;

  const widgetKey = currentScript.getAttribute("data-widget-key");
  const apiUrl = (currentScript.getAttribute("data-api-url") || "").replace(/\/$/, "");
  // Optional locale override on the embed <script data-locale="en"> tag.
  // Absent => "id" (default, tenants are Indonesian). Zero backend change.
  const localeAttr = (currentScript.getAttribute("data-locale") || "").trim().toLowerCase();
  // Optional absolute WebSocket base on the embed <script data-ws-url="wss://..."> tag.
  // Needed when data-api-url is a relative/same-origin path (e.g. a "/api/proxy"
  // that only forwards REST, not WS upgrades): the derived ws base below would be
  // an invalid relative WebSocket URL. When absent, derive ws base from apiUrl as
  // before (correct for the standard absolute-URL tenant embed).
  const wsUrlAttr = (currentScript.getAttribute("data-ws-url") || "").replace(/\/$/, "");
  // Optional launcher placement on the embed <script data-position="bottom-left">
  // tag. Default bottom-right. Lets a tenant move the widget to the other corner.
  const positionAttr = (currentScript.getAttribute("data-position") || "bottom-right")
    .trim()
    .toLowerCase();
  const POS = /^(bottom-right|bottom-left|top-right|top-left)$/.test(positionAttr)
    ? positionAttr
    : "bottom-right";
  const posV = POS.startsWith("top") ? "top" : "bottom"; // vertical anchor edge
  const posH = POS.endsWith("left") ? "left" : "right"; // horizontal anchor edge
  if (!widgetKey || !apiUrl) {
    console.error("[SmartSales Widget] missing data-widget-key or data-api-url");
    return;
  }

  const wsUrl = wsUrlAttr || apiUrl.replace(/^http/, "ws");
  const storageKey = `smartsales_widget_session_${widgetKey}`;
  const PING_INTERVAL_MS = 2 * 60 * 1000; // well under the server's 5-minute idle timeout
  // Reconnect backoff (item 2): exponential base 1s, cap 30s, full jitter.
  const RECONNECT_BASE_MS = 1000;
  const RECONNECT_CAP_MS = 30000;
  const WS_POLICY_CLOSE = 1008; // auth/origin/too-many rejection - do NOT loop

  function getSession(): StoredSession | null {
    try {
      const raw = localStorage.getItem(storageKey);
      return raw ? (JSON.parse(raw) as StoredSession) : null;
    } catch {
      return null;
    }
  }

  function setSession(session: StoredSession) {
    try {
      localStorage.setItem(storageKey, JSON.stringify(session));
    } catch {
      /* localStorage unavailable (private mode, etc) - session just won't persist across reloads */
    }
  }

  // Item 4 (expired-token cleanup): purge the persisted token so a reload
  // doesn't keep replaying an expired/invalid token. Called on a hard 401
  // from the REST API (unambiguous token-expired), NOT on a WS 1008 close -
  // 1008 also covers too-many-connections/origin, where the token is fine.
  function removeSession() {
    try {
      localStorage.removeItem(storageKey);
    } catch {
      /* localStorage unavailable - nothing persisted to remove */
    }
  }

  function genClientMessageId(): string {
    try {
      const c = (globalThis as { crypto?: Crypto }).crypto;
      if (c && typeof c.randomUUID === "function") return c.randomUUID();
    } catch {
      /* fall through to the non-crypto fallback below */
    }
    return `cmid-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 12)}`;
  }

  function prefersReducedMotion(): boolean {
    try {
      return !!window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    } catch {
      return false;
    }
  }

  // Flip company-centric server direction to visitor-centric UI direction.
  // Company "inbound" (a visitor message) => UI "outbound" (right, us); anything
  // else (company "outbound" = an agent reply, OR a missing direction) => UI
  // "inbound" (left, the support team). Keying on "inbound" — not "outbound" —
  // is deliberate: the live WS "message" frame carries only agent replies and
  // does NOT include a direction field, so it must default to the team side
  // (left). Keying on "outbound" defaulted those to the right, making agent
  // replies look like the visitor's own messages.
  function fromServer(m: ServerMessage): WidgetMessage {
    return {
      id: m.id,
      direction: m.direction === "inbound" ? "outbound" : "inbound",
      content: m.content || "",
      sent_at: m.sent_at,
      media_url: m.media_url ?? null,
      attachments: m.attachments || [],
      status: "sent",
    };
  }

  async function apiFetch(path: string, options: RequestInit = {}) {
    const res = await fetch(`${apiUrl}${path}`, {
      ...options,
      headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) {
      const err = new Error(json?.error?.message || json?.message || "Request failed") as Error & {
        status?: number;
      };
      err.status = res.status; // lets callers detect a 401 for token cleanup (item 4)
      throw err;
    }
    return json?.data ?? json;
  }

  class SmartSalesWidget {
    private root: HTMLDivElement;
    private shadow: ShadowRoot;
    private config: WidgetConfig | null = null;
    private strings: WidgetStrings = resolveStrings(localeAttr);
    private session: StoredSession | null = getSession();
    private ws: WebSocket | null = null;
    private pingTimer: number | null = null;
    private reconnectTimer: number | null = null;
    private reconnectAttempts = 0;
    private stoppedReconnect = false;
    private messages: WidgetMessage[] = [];
    // ids of messages already incorporated from server/WS - dedupes a WS
    // redelivery/echo and a history replay of an already-shown message.
    private serverIds = new Set<string>();
    private isOpen = false;
    private unreadCount = 0;
    private titleFlashTimer: number | null = null;
    private originalTitle = "";

    // View state machine: "home" (assistant landing) or "chat" (thread).
    private view: "home" | "chat" = "home";
    // Sticky "you're connected with an agent" system line, set when /start
    // returns assigned:true. Held as a flag (not a message) so it survives a
    // history resync, which rebuilds this.messages from server state.
    private agentConnected = false;
    private menuOpen = false;

    private bubbleEl!: HTMLButtonElement;
    private badgeEl!: HTMLSpanElement;
    private panelEl!: HTMLDivElement;
    private bodyEl!: HTMLDivElement;
    private statusEl!: HTMLDivElement;
    private formEl!: HTMLFormElement;
    private homeViewEl!: HTMLDivElement;
    private chatViewEl!: HTMLDivElement;
    private homeComposerSlot!: HTMLDivElement;
    private chatComposerSlot!: HTMLDivElement;
    private menuEl!: HTMLDivElement;
    private menuWrapEl!: HTMLDivElement;
    private backBtn!: HTMLButtonElement;

    constructor() {
      this.root = document.createElement("div");
      this.root.id = "smartsales-widget-root";
      // Mount on <html>, NOT <body>. A `transform` / `filter` / `perspective` /
      // `will-change` on the host page's <body> (very common with animation
      // libraries, page transitions, some CSS frameworks) establishes a
      // containing block that turns our `position: fixed` bubble/panel into
      // `position: absolute` - which is exactly what pins the widget to the wrong
      // corner and lets it scroll away instead of staying on screen. <html> is far
      // less likely to carry such a property, so fixed positioning stays true to
      // the viewport. Defensive inline reset so a broad host rule like
      // `div { position: relative }` can't turn the root itself into a containing
      // block that would re-trap the fixed children.
      this.root.style.cssText = "position: static; margin: 0; padding: 0; border: 0;";
      (document.documentElement || document.body).appendChild(this.root);
      this.shadow = this.root.attachShadow({ mode: "open" });
    }

    async init() {
      try {
        this.config = await apiFetch(`/public/widget/config/${widgetKey}`);
      } catch (e) {
        console.error("[SmartSales Widget] failed to load config", e);
        return;
      }
      if (!this.config || !this.config.is_widget_enabled) return;

      // Precedence: backend config.locale (future) > data-locale attr > "id".
      this.strings = resolveStrings(this.config.locale || localeAttr, this.config.strings);

      this.render();

      // Stop the title flash / (unread stays until the panel is opened) when
      // the visitor returns to this tab.
      window.addEventListener("focus", () => this.stopTitleFlash());

      if (this.session) {
        // An active session always opens straight into the thread; load
        // history immediately, then connect. connectSocket's onopen resyncs
        // again to catch anything that arrived during the outage.
        this.setView("chat");
        await this.resyncHistory();
        this.connectSocket();
      } else {
        // No session: the home screen is the landing surface when enabled,
        // otherwise fall back to an (empty) chat thread + composer.
        this.setView(this.config.show_home_screen ? "home" : "chat");
      }
    }

    private online(): boolean {
      return !!(this.config!.presence?.online || this.config!.is_within_business_hours);
    }

    private render() {
      const brand = this.config!.brand_color || "#5479EE";
      const brandDark = darken(brand, 0.18);
      const style = document.createElement("style");
      style.textContent = `
        :host { all: initial; }
        * { box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }

        .bubble {
          position: fixed; ${posV}: 20px; ${posH}: 20px; width: 56px; height: 56px;
          border-radius: 50%; background: ${brand}; color: #fff; border: none;
          cursor: pointer; box-shadow: 0 4px 14px rgba(0,0,0,.2); z-index: 2147483000;
          display: flex; align-items: center; justify-content: center; font-size: 26px; overflow: hidden;
        }
        .bubble img { width: 100%; height: 100%; object-fit: cover; }
        .badge {
          position: absolute; top: -4px; right: -4px; min-width: 20px; height: 20px;
          padding: 0 5px; border-radius: 10px; background: #EF4444; color: #fff;
          font-size: 11px; font-weight: 700; line-height: 20px; text-align: center;
          box-shadow: 0 0 0 2px #fff; display: none;
        }
        .badge.show { display: block; }

        .panel {
          position: fixed; ${posV}: 88px; ${posH}: 20px; width: 380px; max-width: calc(100vw - 40px);
          height: 560px; max-height: calc(100vh - 120px); background: #fff; border-radius: 16px;
          box-shadow: 0 12px 40px rgba(0,0,0,.22); display: none; flex-direction: column; overflow: hidden;
          z-index: 2147483000;
        }
        .panel.open { display: flex; }

        .header {
          position: relative; color: #fff; padding: 14px 14px;
          background: linear-gradient(135deg, ${brandDark} 0%, ${brand} 100%);
          display: flex; align-items: center; gap: 10px;
        }
        .header-back {
          display: none; align-items: center; justify-content: center; width: 30px; height: 30px;
          background: none; border: none; color: #fff; font-size: 24px; line-height: 1; cursor: pointer; padding: 0;
        }
        .header-avatar {
          flex: 0 0 auto; width: 38px; height: 38px; border-radius: 10px; overflow: hidden;
          background: rgba(255,255,255,.2); display: flex; align-items: center; justify-content: center; color: #fff;
        }
        .header-avatar img { width: 100%; height: 100%; object-fit: cover; }
        .header-avatar svg { width: 22px; height: 22px; }
        .header-title { flex: 1 1 auto; min-width: 0; }
        .header-title .name { font-weight: 700; font-size: 15px; line-height: 1.2; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
        .header-status { display: flex; align-items: center; gap: 6px; font-size: 12px; font-weight: 400; opacity: .92; margin-top: 2px; }
        .dot { width: 8px; height: 8px; border-radius: 50%; flex: 0 0 auto; box-shadow: 0 0 0 2px rgba(255,255,255,.25); }
        .dot.on { background: #22C55E; }
        .dot.off { background: #cbd5e1; }
        .header-actions { flex: 0 0 auto; display: flex; align-items: center; gap: 2px; margin-left: auto; }
        .icon-btn {
          background: none; border: none; color: #fff; cursor: pointer; padding: 0; line-height: 1;
          width: 30px; height: 30px; border-radius: 8px; display: flex; align-items: center; justify-content: center;
          font-size: 18px;
        }
        .icon-btn:hover { background: rgba(255,255,255,.15); }
        .menu-wrap { position: relative; }
        .menu {
          display: none; position: absolute; top: 34px; right: 0; min-width: 150px; background: #fff;
          border: 1px solid #E5E7EB; border-radius: 10px; box-shadow: 0 8px 24px rgba(0,0,0,.16);
          padding: 4px; z-index: 5;
        }
        .menu.open { display: block; }
        .menu-item {
          display: block; width: 100%; text-align: left; background: none; border: none; cursor: pointer;
          padding: 8px 10px; border-radius: 7px; font-size: 13px; color: #111827;
        }
        .menu-item:hover { background: #F3F4F6; }

        .status { display: none; padding: 6px 12px; background: #F3F4F6; color: #6B7280; font-size: 11px; text-align: center; }
        .status.show { display: block; }
        .offline { padding: 10px 12px; background: #FEF3C7; color: #92400E; font-size: 12px; }

        /* view containers - only one is display:flex at a time */
        .view { flex: 1 1 auto; min-height: 0; flex-direction: column; }

        /* ---- Home view ---- */
        .home-scroll { flex: 1 1 auto; min-height: 0; overflow-y: auto; padding: 18px 16px 10px; background: #fff; }
        .home-greet { font-size: 14px; color: #6B7280; }
        .home-headline { font-size: 22px; font-weight: 700; color: #0F172A; line-height: 1.25; margin: 2px 0 6px; }
        .home-sub { font-size: 13px; color: #6B7280; line-height: 1.45; margin-bottom: 14px; }
        .cards { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
        .card {
          display: flex; align-items: flex-start; gap: 10px; text-align: left; cursor: pointer;
          background: #fff; border: 1px solid #E9EDF3; border-radius: 12px; padding: 12px; width: 100%;
          transition: border-color .15s, box-shadow .15s, transform .05s;
        }
        .card:hover { border-color: ${brand}; box-shadow: 0 4px 14px rgba(15,23,42,.08); }
        .card:active { transform: translateY(1px); }
        .card-icon { flex: 0 0 auto; width: 34px; height: 34px; border-radius: 9px; display: flex; align-items: center; justify-content: center; }
        .card-icon svg { width: 18px; height: 18px; }
        .card-body { flex: 1 1 auto; min-width: 0; }
        .card-label { font-size: 13px; font-weight: 700; color: #111827; line-height: 1.25; }
        .card-desc { font-size: 12px; color: #6B7280; line-height: 1.35; margin-top: 2px; }
        .card-chevron { flex: 0 0 auto; color: #C0C7D2; align-self: center; }
        .card-chevron svg { width: 16px; height: 16px; }

        .handoff { margin-top: 16px; padding: 14px; border: 1px solid #E9EDF3; border-radius: 12px; background: #FAFBFC; }
        .handoff-avatars { display: flex; margin-bottom: 8px; }
        .avatar { width: 28px; height: 28px; border-radius: 50%; border: 2px solid #fff; background: #E5E7EB; object-fit: cover; margin-left: -8px; }
        .avatar:first-child { margin-left: 0; }
        .handoff-text .h { font-size: 13px; font-weight: 700; color: #111827; }
        .handoff-text .s { font-size: 12px; color: #6B7280; margin-top: 1px; }
        .handoff-btn {
          margin-top: 10px; width: 100%; background: #fff; color: ${brand}; border: 1.5px solid ${brand};
          border-radius: 9px; padding: 9px 12px; font-size: 13px; font-weight: 700; cursor: pointer;
        }
        .handoff-btn:hover { background: ${brand}; color: #fff; }

        .privacy { display: flex; align-items: center; gap: 6px; padding: 9px 16px; font-size: 11px; color: #94A3B8; border-top: 1px solid #F1F3F6; }
        .privacy svg { width: 13px; height: 13px; flex: 0 0 auto; }
        .privacy a { color: ${brand}; text-decoration: none; }
        .privacy a:hover { text-decoration: underline; }

        /* ---- Chat view ---- */
        .body { flex: 1 1 auto; min-height: 0; overflow-y: auto; padding: 12px; display: flex; flex-direction: column; gap: 8px; background: #F9FAFB; }
        .msg { max-width: 80%; padding: 8px 12px; border-radius: 12px; font-size: 13px; line-height: 1.4; white-space: pre-wrap; word-break: break-word; }
        .msg.inbound { align-self: flex-start; background: #fff; border: 1px solid #E5E7EB; color: #111827; }
        .msg.outbound { align-self: flex-end; background: ${brand}; color: #fff; }
        .msg.failed { opacity: .85; }
        .msg .att-image { display: block; margin-top: 6px; }
        .msg .att-image img { max-width: 100%; border-radius: 8px; display: block; }
        .msg .att-file { display: inline-block; margin-top: 6px; font-size: 12px; text-decoration: underline; color: inherit; word-break: break-all; }
        .retry { display: block; margin-top: 6px; background: none; border: none; padding: 0; cursor: pointer; font-size: 11px; font-weight: 600; color: #FCA5A5; text-align: left; }
        .msg.inbound .retry { color: #DC2626; }
        .sys-line { align-self: center; max-width: 92%; text-align: center; font-size: 11px; color: #6B7280; background: #EEF2F7; padding: 4px 12px; border-radius: 999px; margin: 2px auto; }

        /* ---- Composer (shared between views, re-parented on view switch) ---- */
        .composer { display: flex; align-items: flex-end; gap: 8px; padding: 10px 12px; border-top: 1px solid #E5E7EB; background: #fff; }
        /* 16px (not 13px) so iOS Safari doesn't zoom the page on focus (item 2 a11y). */
        .composer textarea {
          flex: 1 1 auto; border: 1px solid #E5E7EB; border-radius: 20px; padding: 9px 14px; font-size: 16px;
          outline: none; resize: none; max-height: 96px; line-height: 1.35;
        }
        .composer textarea:focus { border-color: ${brand}; }
        button.send {
          flex: 0 0 auto; background: ${brand}; color: #fff; border: none; border-radius: 50%;
          width: 38px; height: 38px; cursor: pointer; display: flex; align-items: center; justify-content: center;
        }
        button.send svg { width: 18px; height: 18px; }
        button.send:disabled { opacity: .5; cursor: default; }

        /* ---- Mobile: panel goes full-screen, reveal the back affordance ---- */
        @media (max-width: 480px) {
          .panel {
            top: 0; left: 0; right: 0; bottom: 0; width: 100%; height: 100%;
            max-width: 100%; max-height: 100%; border-radius: 0;
          }
          .cards { grid-template-columns: 1fr; }
          .header-back.show { display: flex; }
        }
      `;
      this.shadow.appendChild(style);

      // ---- Launcher bubble (keeps unread badge behavior exactly) ----
      this.bubbleEl = document.createElement("button");
      this.bubbleEl.className = "bubble";
      this.bubbleEl.setAttribute("aria-label", this.strings.openChat);
      if (this.config!.bot_avatar_url) {
        const img = document.createElement("img");
        img.src = this.config!.bot_avatar_url;
        img.alt = "";
        this.bubbleEl.appendChild(img);
      } else {
        const glyph = document.createElement("span");
        glyph.textContent = "💬";
        this.bubbleEl.appendChild(glyph);
      }
      this.bubbleEl.onclick = () => this.toggle();
      this.badgeEl = document.createElement("span");
      this.badgeEl.className = "badge";
      this.badgeEl.setAttribute("aria-hidden", "true");
      this.bubbleEl.appendChild(this.badgeEl);
      this.shadow.appendChild(this.bubbleEl);

      // ---- Panel ----
      this.panelEl = document.createElement("div");
      this.panelEl.className = "panel";

      this.panelEl.appendChild(this.buildHeader());

      // Subtle connection-state line (item 2): only shown once we've given up
      // reconnecting after an auth/policy close, so the visitor knows the
      // live channel is down rather than silently swallowing agent replies.
      this.statusEl = document.createElement("div");
      this.statusEl.className = "status";
      this.statusEl.setAttribute("role", "status");
      this.statusEl.textContent = this.strings.disconnected;
      this.panelEl.appendChild(this.statusEl);

      if (!this.config!.is_within_business_hours && this.config!.offline_message) {
        const offline = document.createElement("div");
        offline.className = "offline";
        offline.textContent = this.config!.offline_message;
        this.panelEl.appendChild(offline);
      }

      // Shared composer, built once and re-parented between the two views.
      this.formEl = this.buildForm();

      this.homeViewEl = this.buildHomeView();
      this.chatViewEl = this.buildChatView();
      this.panelEl.appendChild(this.homeViewEl);
      this.panelEl.appendChild(this.chatViewEl);

      // Close the overflow menu on any click elsewhere inside the panel.
      this.panelEl.addEventListener("click", (e) => {
        if (this.menuOpen && !this.menuWrapEl.contains(e.target as Node)) this.closeMenu();
      });

      this.shadow.appendChild(this.panelEl);
      this.renderMessages();
    }

    private buildHeader(): HTMLDivElement {
      const header = document.createElement("div");
      header.className = "header";

      // Back affordance (mobile full-screen only, chat view only).
      this.backBtn = document.createElement("button");
      this.backBtn.className = "header-back";
      this.backBtn.setAttribute("aria-label", this.strings.back);
      this.backBtn.textContent = "‹";
      this.backBtn.onclick = () => this.setView("home");
      header.appendChild(this.backBtn);

      // Bot avatar tile.
      const avatar = document.createElement("div");
      avatar.className = "header-avatar";
      if (this.config!.bot_avatar_url) {
        const img = document.createElement("img");
        img.src = this.config!.bot_avatar_url;
        img.alt = "";
        avatar.appendChild(img);
      } else {
        avatar.appendChild(svgEl(IC_ROBOT));
      }
      header.appendChild(avatar);

      // Title + status sub-line.
      const titleWrap = document.createElement("div");
      titleWrap.className = "header-title";
      const name = document.createElement("div");
      name.className = "name";
      name.textContent = this.config!.bot_name || this.config!.title || "";
      titleWrap.appendChild(name);

      const status = document.createElement("div");
      status.className = "header-status";
      const online = this.online();
      const dot = document.createElement("span");
      dot.className = `dot ${online ? "on" : "off"}`;
      status.appendChild(dot);
      const statusText = document.createElement("span");
      const word = online ? this.strings.online : this.strings.offlineShort;
      const rt = (this.config!.response_time_label || "").trim();
      statusText.textContent = rt ? `${word} · ${rt}` : word;
      status.appendChild(statusText);
      titleWrap.appendChild(status);
      header.appendChild(titleWrap);

      // Actions: overflow menu + close.
      const actions = document.createElement("div");
      actions.className = "header-actions";

      this.menuWrapEl = document.createElement("div");
      this.menuWrapEl.className = "menu-wrap";
      const menuBtn = document.createElement("button");
      menuBtn.className = "icon-btn";
      menuBtn.setAttribute("aria-label", this.strings.menu);
      menuBtn.setAttribute("aria-haspopup", "true");
      menuBtn.textContent = "⋮";
      menuBtn.onclick = () => this.toggleMenu();
      this.menuWrapEl.appendChild(menuBtn);

      this.menuEl = document.createElement("div");
      this.menuEl.className = "menu";
      this.menuEl.setAttribute("role", "menu");
      const startOver = document.createElement("button");
      startOver.className = "menu-item";
      startOver.setAttribute("role", "menuitem");
      startOver.textContent = this.strings.startOver;
      startOver.onclick = () => this.resetAll();
      this.menuEl.appendChild(startOver);
      this.menuWrapEl.appendChild(this.menuEl);
      actions.appendChild(this.menuWrapEl);

      const closeBtn = document.createElement("button");
      closeBtn.className = "icon-btn";
      closeBtn.setAttribute("aria-label", this.strings.closeChat);
      closeBtn.textContent = "✕";
      closeBtn.onclick = () => this.toggle();
      actions.appendChild(closeBtn);

      header.appendChild(actions);
      return header;
    }

    private buildHomeView(): HTMLDivElement {
      const home = document.createElement("div");
      home.className = "view home";

      const scroll = document.createElement("div");
      scroll.className = "home-scroll";

      const greet = document.createElement("div");
      greet.className = "home-greet";
      greet.textContent = this.strings.greetingHi;
      scroll.appendChild(greet);

      const headline = document.createElement("div");
      headline.className = "home-headline";
      headline.textContent = (this.config!.home_headline || "").trim() || this.strings.homeHeadline;
      scroll.appendChild(headline);

      const sub = document.createElement("div");
      sub.className = "home-sub";
      sub.textContent =
        (this.config!.home_subtext || "").trim() ||
        (this.config!.greeting_message || "").trim() ||
        this.strings.homeSubtext;
      scroll.appendChild(sub);

      const actions = this.config!.quick_actions || [];
      if (actions.length) {
        const grid = document.createElement("div");
        grid.className = "cards";
        for (const a of actions) grid.appendChild(this.buildCard(a));
        scroll.appendChild(grid);
      }

      if (this.config!.enable_human_handoff) scroll.appendChild(this.buildHandoff());

      home.appendChild(scroll);

      // Composer slot (form is re-parented here when the home view is active).
      this.homeComposerSlot = document.createElement("div");
      this.homeComposerSlot.className = "composer-slot";
      home.appendChild(this.homeComposerSlot);

      // Privacy footer.
      const priv = (this.config!.privacy_footer_text || "").trim();
      if (priv) {
        const footer = document.createElement("div");
        footer.className = "privacy";
        footer.appendChild(svgEl(IC_SHIELD));
        if (this.config!.privacy_url) {
          const a = document.createElement("a");
          a.href = this.config!.privacy_url;
          a.target = "_blank";
          a.rel = "noopener noreferrer";
          a.textContent = priv;
          footer.appendChild(a);
        } else {
          const span = document.createElement("span");
          span.textContent = priv;
          footer.appendChild(span);
        }
        home.appendChild(footer);
      }

      return home;
    }

    private buildCard(a: QuickAction): HTMLButtonElement {
      const card = document.createElement("button");
      card.type = "button";
      card.className = "card";

      const meta = iconMeta(a.icon);
      const icon = svgEl(meta.svg, "card-icon");
      icon.style.background = meta.bg;
      icon.style.color = meta.fg;
      card.appendChild(icon);

      const body = document.createElement("div");
      body.className = "card-body";
      const label = document.createElement("div");
      label.className = "card-label";
      label.textContent = a.label || "";
      body.appendChild(label);
      const desc = (a.description || "").trim();
      if (desc) {
        const d = document.createElement("div");
        d.className = "card-desc";
        d.textContent = desc;
        body.appendChild(d);
      }
      card.appendChild(body);

      card.appendChild(svgEl(IC_CHEVRON, "card-chevron"));

      card.onclick = () => this.onQuickAction(a);
      return card;
    }

    private buildHandoff(): HTMLDivElement {
      const box = document.createElement("div");
      box.className = "handoff";

      const avatars = this.config!.presence?.avatars || [];
      const showAvatars = this.config!.show_presence !== false && avatars.length > 0;
      if (showAvatars) {
        const cluster = document.createElement("div");
        cluster.className = "handoff-avatars";
        for (const url of avatars.slice(0, 3)) {
          const img = document.createElement("img");
          img.className = "avatar";
          img.src = url;
          img.alt = "";
          cluster.appendChild(img);
        }
        box.appendChild(cluster);
      }

      const text = document.createElement("div");
      text.className = "handoff-text";
      const h = document.createElement("div");
      h.className = "h";
      h.textContent = this.strings.needMoreHelp;
      const s = document.createElement("div");
      s.className = "s";
      s.textContent = this.strings.teamHere;
      text.appendChild(h);
      text.appendChild(s);
      box.appendChild(text);

      const btn = document.createElement("button");
      btn.type = "button";
      btn.className = "handoff-btn";
      btn.textContent = (this.config!.handoff_label || "").trim() || this.strings.handoffDefault;
      btn.onclick = () => this.onHandoff();
      box.appendChild(btn);

      return box;
    }

    private buildChatView(): HTMLDivElement {
      const chat = document.createElement("div");
      chat.className = "view chat";

      this.bodyEl = document.createElement("div");
      this.bodyEl.className = "body";
      // a11y (item 2): announce agent replies to screen readers as they arrive.
      this.bodyEl.setAttribute("role", "log");
      this.bodyEl.setAttribute("aria-live", "polite");
      this.bodyEl.setAttribute("aria-atomic", "false");
      chat.appendChild(this.bodyEl);

      this.chatComposerSlot = document.createElement("div");
      this.chatComposerSlot.className = "composer-slot";
      chat.appendChild(this.chatComposerSlot);

      return chat;
    }

    private buildForm(): HTMLFormElement {
      // Anonymous start: no mandatory pre-chat name/email form. The backend
      // creates the contact from the first message; the first send never
      // blocks on identity capture.
      const form = document.createElement("form");
      form.className = "composer";

      const messageInput = document.createElement("textarea");
      messageInput.placeholder = this.strings.typeMessage;
      messageInput.setAttribute("aria-label", this.strings.typeMessage);
      messageInput.name = "message";
      messageInput.rows = 1;
      // Enter sends, Shift+Enter inserts a newline (keyboard operability, item 2).
      messageInput.addEventListener("keydown", (e) => {
        if (e.key === "Enter" && !e.shiftKey) {
          e.preventDefault();
          if (typeof form.requestSubmit === "function") form.requestSubmit();
          else void this.handleSubmit(form, sendBtn);
        }
      });
      form.appendChild(messageInput);

      const sendBtn = document.createElement("button");
      sendBtn.type = "submit";
      sendBtn.className = "send";
      sendBtn.setAttribute("aria-label", this.strings.send);
      sendBtn.appendChild(svgEl(IC_SEND));
      form.appendChild(sendBtn);

      form.onsubmit = (e) => {
        e.preventDefault();
        void this.handleSubmit(form, sendBtn);
      };

      return form;
    }

    private async handleSubmit(form: HTMLFormElement, sendBtn: HTMLButtonElement) {
      const data = new FormData(form);
      const message = (data.get("message") as string)?.trim();
      if (!message) return;
      form.reset();
      await this.sendVisitorMessage(message, null, null, sendBtn);
    }

    // Unified optimistic-send path for every visitor-initiated message: a
    // free-text composer submit, a quick-action card, or the handoff button.
    // When there's no session yet this becomes the /start call and carries the
    // optional routing fields (target_queue_id / action_id); afterwards it's a
    // plain /messages post. Always switches into the chat view so the visitor
    // sees their own first bubble land in the thread.
    private async sendVisitorMessage(
      content: string,
      targetQueueId: string | null,
      actionId: string | null,
      sendBtn?: HTMLButtonElement,
    ) {
      const msg: WidgetMessage = {
        direction: "outbound",
        content,
        client_message_id: genClientMessageId(),
        status: "sending",
        // Routing context is only meaningful for the first message (/start);
        // held so a retry re-POSTs the SAME start payload.
        startCtx: this.session ? undefined : { target_queue_id: targetQueueId, action_id: actionId },
      };
      this.messages.push(msg);
      if (this.view !== "chat") this.setView("chat");
      this.renderMessages();
      await this.attemptSend(msg, sendBtn);
    }

    private onQuickAction(a: QuickAction) {
      const content =
        (a.prefill || "").trim() || `${this.strings.helpWithPrefix}${a.label || ""}`;
      void this.sendVisitorMessage(content, a.target_queue_id ?? null, a.id ?? null);
    }

    private onHandoff() {
      void this.sendVisitorMessage(
        this.strings.talkToHuman,
        this.config!.handoff_queue_id ?? null,
        null,
      );
    }

    private async attemptSend(msg: WidgetMessage, sendBtn?: HTMLButtonElement) {
      msg.status = "sending";
      this.renderMessages();
      if (sendBtn) sendBtn.disabled = true;
      try {
        if (!this.session) {
          // Optimistic render with a fresh idempotency key. A retry re-POSTs the
          // SAME client_message_id so the backend dedup makes it safe (item 4).
          const result = await apiFetch(`/public/widget/start`, {
            method: "POST",
            body: JSON.stringify({
              widget_key: widgetKey,
              message: msg.content,
              // Anonymous start: visitor_name/visitor_email omitted - backend
              // creates the contact. Routing fields added for quick-action/handoff.
              target_queue_id: msg.startCtx?.target_queue_id ?? undefined,
              action_id: msg.startCtx?.action_id ?? undefined,
              page_url: window.location.href,
            }),
          });
          this.session = { visitor_token: result.visitor_token, conversation_id: result.conversation_id };
          setSession(this.session);
          // A brand-new session must not inherit a prior "stop reconnecting"
          // flag (e.g. from an earlier expired-token purge) - clear it before
          // (re)connecting so the fresh conversation keeps full WS resilience.
          this.stoppedReconnect = false;
          // /start now reports whether an agent was assigned immediately.
          if (result.assigned) this.agentConnected = true;
          this.connectSocket();
        } else {
          await apiFetch(`/public/widget/messages`, {
            method: "POST",
            headers: { Authorization: `Bearer ${this.session.visitor_token}` },
            body: JSON.stringify({ content: msg.content, client_message_id: msg.client_message_id }),
          });
        }
        msg.status = "sent";
      } catch (e) {
        console.error("[SmartSales Widget] send failed", e);
        msg.status = "failed";
        // Expired/revoked token on an authenticated send: purge it (item 4).
        if ((e as { status?: number })?.status === 401) this.clearSession();
      } finally {
        if (sendBtn) sendBtn.disabled = false;
        this.renderMessages();
      }
    }

    private buildAttachmentEl(att: WidgetAttachment): HTMLElement | null {
      const url = (att.media_url || "").trim();
      if (!url) return null;
      const ct = (att.content_type || "").toLowerCase();
      const isImage = ct.startsWith("image/") || /\.(png|jpe?g|gif|webp|bmp|svg)(\?|$)/i.test(url);

      const link = document.createElement("a");
      link.href = url;
      link.target = "_blank";
      link.rel = "noopener noreferrer";

      if (isImage) {
        link.className = "att-image";
        const img = document.createElement("img");
        img.src = url;
        img.alt = att.filename || this.strings.attachment;
        img.loading = "lazy";
        link.appendChild(img);
      } else {
        link.className = "att-file";
        link.textContent = `📎 ${att.filename || this.strings.downloadAttachment}`;
      }
      return link;
    }

    private renderMessages() {
      this.bodyEl.innerHTML = "";

      // Welcome greeting bubble on an empty thread (preserves greeting_message
      // for the no-home-screen path). Only while the thread has no messages,
      // so it never duplicates real server-persisted content.
      if (this.view === "chat" && this.messages.length === 0) {
        const greeting = (this.config!.greeting_message || "").trim();
        if (greeting) {
          const g = document.createElement("div");
          g.className = "msg inbound";
          g.textContent = greeting;
          this.bodyEl.appendChild(g);
        }
      }

      for (const m of this.messages) {
        const el = document.createElement("div");
        el.className = `msg ${m.direction}${m.status === "failed" ? " failed" : ""}`;

        if (m.content) {
          const text = document.createElement("div");
          text.className = "msg-text";
          text.textContent = m.content;
          el.appendChild(text);
        }

        const media =
          m.attachments && m.attachments.length
            ? m.attachments
            : m.media_url
              ? [{ media_url: m.media_url } as WidgetAttachment]
              : [];
        for (const att of media) {
          const attEl = this.buildAttachmentEl(att);
          if (attEl) el.appendChild(attEl);
        }

        if (m.direction === "outbound" && m.status === "failed") {
          const retry = document.createElement("button");
          retry.type = "button";
          retry.className = "retry";
          retry.textContent = this.strings.failedRetry;
          retry.onclick = () => void this.attemptSend(m);
          el.appendChild(retry);
        }

        this.bodyEl.appendChild(el);
      }

      // Sticky "connected with an agent" system line (assigned:true from /start).
      if (this.agentConnected) {
        const sys = document.createElement("div");
        sys.className = "sys-line";
        sys.textContent = this.strings.connectedAgent;
        this.bodyEl.appendChild(sys);
      }

      this.bodyEl.scrollTop = this.bodyEl.scrollHeight;
    }

    // Re-fetch full history and reconcile (item 3). Server state is
    // authoritative for everything persisted; we keep only local outbound
    // messages that are still in-flight or failed (not yet on the server),
    // so agent messages that arrived during an outage show up without
    // duplicating anything already rendered.
    private async resyncHistory() {
      if (!this.session) return;
      try {
        const conv = await apiFetch(`/public/widget/conversation`, {
          headers: { Authorization: `Bearer ${this.session.visitor_token}` },
        });
        const serverMsgs: WidgetMessage[] = (conv.messages || []).map(fromServer);
        const pendingLocal = this.messages.filter(
          (m) => m.direction === "outbound" && (m.status === "sending" || m.status === "failed"),
        );
        this.serverIds = new Set(
          serverMsgs.filter((m): m is WidgetMessage & { id: string } => !!m.id).map((m) => m.id),
        );
        this.messages = [...serverMsgs, ...pendingLocal];
        this.renderMessages();
      } catch (e) {
        // A 401 means the visitor token expired/was revoked: purge it so a
        // reload starts a fresh session rather than replaying a dead token
        // (item 4). Any other failure is non-fatal - keep what's rendered.
        if ((e as { status?: number })?.status === 401) this.clearSession();
      }
    }

    // Item 4: drop the persisted + in-memory token and stop the (now-dead)
    // reconnect loop. Keeps the rendered thread so the visitor can simply send
    // again, which transparently opens a fresh conversation via /start.
    private clearSession() {
      removeSession();
      this.session = null;
      this.serverIds = new Set();
      this.stoppedReconnect = true;
      this.agentConnected = false;
    }

    // Explicit "Start over" (overflow menu): tear the live session all the way
    // down and return to the landing surface.
    private resetAll() {
      this.closeMenu();
      this.stoppedReconnect = true;
      if (this.reconnectTimer) {
        window.clearTimeout(this.reconnectTimer);
        this.reconnectTimer = null;
      }
      if (this.pingTimer) {
        window.clearInterval(this.pingTimer);
        this.pingTimer = null;
      }
      if (this.ws) {
        try {
          this.ws.close();
        } catch {
          /* ignore */
        }
        this.ws = null;
      }
      removeSession();
      this.session = null;
      this.messages = [];
      this.serverIds = new Set();
      this.agentConnected = false;
      this.reconnectAttempts = 0;
      // Allow the next conversation to reconnect normally.
      this.stoppedReconnect = false;
      this.renderMessages();
      this.setView(this.config!.show_home_screen ? "home" : "chat");
    }

    private connectSocket() {
      if (!this.session || this.ws) return;
      const socket = new WebSocket(`${wsUrl}/public/widget/ws?token=${encodeURIComponent(this.session.visitor_token)}`);
      this.ws = socket;

      socket.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data) as ServerMessage & { type?: string };
          if (data.type === "message") {
            // Dedupe redelivery/echo by id (item 3).
            if (data.id && this.serverIds.has(data.id)) return;
            if (data.id) this.serverIds.add(data.id);
            const msg = fromServer(data);
            this.messages.push(msg);
            this.renderMessages();
            // Unread badge (item 6): only agent (inbound) frames, only while closed.
            if (!this.isOpen && msg.direction === "inbound") this.incrementUnread();
          }
        } catch {
          /* ignore malformed frames */
        }
      };

      socket.onopen = () => {
        this.reconnectAttempts = 0; // reset backoff on a successful open
        this.setDisconnected(false);
        this.pingTimer = window.setInterval(() => {
          if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: "ping" }));
        }, PING_INTERVAL_MS);
        // Catch anything missed while the socket was down (item 3).
        void this.resyncHistory();
      };

      socket.onclose = (event) => {
        if (this.pingTimer) window.clearInterval(this.pingTimer);
        this.pingTimer = null;
        this.ws = null;
        // Auth/origin/too-many-connections close: reconnecting can't fix it,
        // so stop looping and show a subtle disconnected state (item 2).
        if (event.code === WS_POLICY_CLOSE) {
          this.stoppedReconnect = true;
          this.setDisconnected(true);
          return;
        }
        this.scheduleReconnect();
      };
    }

    private scheduleReconnect() {
      if (this.stoppedReconnect || this.reconnectTimer) return;
      // Exponential backoff with FULL jitter: delay in [0, min(cap, base*2^n)).
      const ceiling = Math.min(RECONNECT_CAP_MS, RECONNECT_BASE_MS * Math.pow(2, this.reconnectAttempts));
      const delay = Math.random() * ceiling;
      this.reconnectAttempts++;
      this.reconnectTimer = window.setTimeout(() => {
        this.reconnectTimer = null;
        this.connectSocket();
      }, delay);
    }

    private setDisconnected(on: boolean) {
      this.statusEl.classList.toggle("show", on);
    }

    private incrementUnread() {
      this.unreadCount++;
      this.badgeEl.textContent = this.unreadCount > 99 ? "99+" : String(this.unreadCount);
      this.badgeEl.classList.add("show");
      this.startTitleFlash();
    }

    private clearUnread() {
      this.unreadCount = 0;
      this.badgeEl.classList.remove("show");
      this.badgeEl.textContent = "";
      this.stopTitleFlash();
    }

    // Optional, tasteful title flash (item 6). Suppressed under
    // prefers-reduced-motion, and it ALWAYS restores the host page's original
    // <title> - this runs on arbitrary tenant sites, so it must leave no trace.
    private startTitleFlash() {
      if (prefersReducedMotion() || this.titleFlashTimer || document.hasFocus()) return;
      this.originalTitle = document.title;
      let alt = false;
      this.titleFlashTimer = window.setInterval(() => {
        document.title = alt ? this.originalTitle : `💬 ${this.strings.newMessage}`;
        alt = !alt;
      }, 1200);
    }

    private stopTitleFlash() {
      if (this.titleFlashTimer) {
        window.clearInterval(this.titleFlashTimer);
        this.titleFlashTimer = null;
        if (this.originalTitle) document.title = this.originalTitle;
      }
    }

    private toggleMenu() {
      this.menuOpen = !this.menuOpen;
      this.menuEl.classList.toggle("open", this.menuOpen);
    }

    private closeMenu() {
      this.menuOpen = false;
      this.menuEl.classList.remove("open");
    }

    private setView(v: "home" | "chat") {
      this.view = v;
      this.homeViewEl.style.display = v === "home" ? "flex" : "none";
      this.chatViewEl.style.display = v === "chat" ? "flex" : "none";
      // Re-parent the shared composer into the active view's slot.
      const slot = v === "home" ? this.homeComposerSlot : this.chatComposerSlot;
      slot.appendChild(this.formEl);
      // Back affordance only makes sense returning from chat to a home screen
      // (its own CSS restricts it to mobile full-screen).
      this.backBtn.classList.toggle("show", v === "chat" && !!this.config!.show_home_screen);
      if (v === "chat") this.renderMessages();
    }

    private toggle() {
      this.isOpen = !this.isOpen;
      this.panelEl.classList.toggle("open", this.isOpen);
      if (!this.isOpen) this.closeMenu();
      if (this.isOpen) {
        this.clearUnread();
        // a11y (item 2): move focus into the composer when the panel opens.
        const input = this.formEl?.querySelector('textarea[name="message"]') as HTMLTextAreaElement | null;
        if (input) window.setTimeout(() => input.focus(), 0);
      }
    }
  }

  function escapeHtml(s: string): string {
    const div = document.createElement("div");
    div.textContent = s;
    return div.innerHTML;
  }
  void escapeHtml; // retained for compatibility; render layer uses textContent.

  function boot() {
    new SmartSalesWidget().init();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
