/**
 * SmartSales Web Widget - embeddable chat bubble.
 *
 * Deliberately vanilla TypeScript (no React/Preact) rendered into a Shadow
 * DOM: this script runs on a THIRD-PARTY tenant website, not inside
 * supercontact-web itself, so it must not bloat the host page's bundle or
 * collide with whatever framework/CSS that page already uses. See plans/
 * for the full architecture rationale.
 *
 * Reads its own <script data-widget-key="..." data-api-url="..."> tag via
 * document.currentScript - both attributes are generated by the tenant's
 * Settings > Web Widget page (WebWidgetEmbedGuide.tsx) at copy time, so
 * this bundle itself never hardcodes an environment.
 */

interface WidgetConfig {
  title: string;
  greeting_message: string;
  brand_color: string;
  is_widget_enabled: boolean;
  is_within_business_hours: boolean;
  offline_message?: string | null;
}

interface StoredSession {
  visitor_token: string;
  conversation_id: string;
}

interface WidgetMessage {
  id?: string;
  direction: "inbound" | "outbound";
  content: string;
  sent_at?: string;
}

(function () {
  const currentScript = document.currentScript as HTMLScriptElement | null;
  if (!currentScript) return;

  const widgetKey = currentScript.getAttribute("data-widget-key");
  const apiUrl = (currentScript.getAttribute("data-api-url") || "").replace(/\/$/, "");
  if (!widgetKey || !apiUrl) {
    console.error("[SmartSales Widget] missing data-widget-key or data-api-url");
    return;
  }

  const wsUrl = apiUrl.replace(/^http/, "ws");
  const storageKey = `smartsales_widget_session_${widgetKey}`;
  const PING_INTERVAL_MS = 2 * 60 * 1000; // well under the server's 5-minute idle timeout

  function getSession(): StoredSession | null {
    try {
      const raw = localStorage.getItem(storageKey);
      return raw ? (JSON.parse(raw) as StoredSession) : null;
    } catch {
      return null;
    }
  }

  function setSession(session: StoredSession) {
    try {
      localStorage.setItem(storageKey, JSON.stringify(session));
    } catch {
      /* localStorage unavailable (private mode, etc) - session just won't persist across reloads */
    }
  }

  async function apiFetch(path: string, options: RequestInit = {}) {
    const res = await fetch(`${apiUrl}${path}`, {
      ...options,
      headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) {
      throw new Error(json?.error?.message || json?.message || "Request failed");
    }
    return json?.data ?? json;
  }

  class SmartSalesWidget {
    private root: HTMLDivElement;
    private shadow: ShadowRoot;
    private config: WidgetConfig | null = null;
    private session: StoredSession | null = getSession();
    private ws: WebSocket | null = null;
    private pingTimer: number | null = null;
    private messages: WidgetMessage[] = [];
    private isOpen = false;

    private bubbleEl!: HTMLButtonElement;
    private panelEl!: HTMLDivElement;
    private bodyEl!: HTMLDivElement;
    private formEl!: HTMLFormElement;

    constructor() {
      this.root = document.createElement("div");
      this.root.id = "smartsales-widget-root";
      document.body.appendChild(this.root);
      this.shadow = this.root.attachShadow({ mode: "open" });
    }

    async init() {
      try {
        this.config = await apiFetch(`/public/widget/config/${widgetKey}`);
      } catch (e) {
        console.error("[SmartSales Widget] failed to load config", e);
        return;
      }
      if (!this.config || !this.config.is_widget_enabled) return;

      this.render();

      if (this.session) {
        try {
          const conv = await apiFetch(`/public/widget/conversation`, {
            headers: { Authorization: `Bearer ${this.session.visitor_token}` },
          });
          this.messages = conv.messages || [];
          this.connectSocket();
        } catch {
          // stale/expired token - drop it, visitor starts a fresh conversation next time they chat
          this.session = null;
        }
      }
    }

    private render() {
      const brand = this.config!.brand_color || "#5479EE";
      const style = document.createElement("style");
      style.textContent = `
        :host { all: initial; }
        * { box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
        .bubble {
          position: fixed; bottom: 20px; right: 20px; width: 56px; height: 56px;
          border-radius: 50%; background: ${brand}; color: #fff; border: none;
          cursor: pointer; box-shadow: 0 4px 14px rgba(0,0,0,.2); z-index: 2147483000;
          display: flex; align-items: center; justify-content: center; font-size: 26px;
        }
        .panel {
          position: fixed; bottom: 88px; right: 20px; width: 340px; max-width: calc(100vw - 40px);
          height: 480px; max-height: calc(100vh - 120px); background: #fff; border-radius: 12px;
          box-shadow: 0 8px 30px rgba(0,0,0,.2); display: none; flex-direction: column; overflow: hidden;
          z-index: 2147483000;
        }
        .panel.open { display: flex; }
        .header { background: ${brand}; color: #fff; padding: 14px 16px; font-weight: 600; font-size: 15px; }
        .header p { margin: 2px 0 0; font-size: 12px; font-weight: 400; opacity: .85; }
        .body { flex: 1; overflow-y: auto; padding: 12px; display: flex; flex-direction: column; gap: 8px; background: #F9FAFB; }
        .msg { max-width: 80%; padding: 8px 12px; border-radius: 10px; font-size: 13px; line-height: 1.4; white-space: pre-wrap; word-break: break-word; }
        .msg.inbound { align-self: flex-start; background: #fff; border: 1px solid #E5E7EB; color: #111827; }
        .msg.outbound { align-self: flex-end; background: ${brand}; color: #fff; }
        .offline { padding: 10px 12px; background: #FEF3C7; color: #92400E; font-size: 12px; }
        form { display: flex; flex-direction: column; gap: 8px; padding: 12px; border-top: 1px solid #E5E7EB; }
        input, textarea { border: 1px solid #E5E7EB; border-radius: 8px; padding: 8px 10px; font-size: 13px; outline: none; }
        input:focus, textarea:focus { border-color: ${brand}; }
        button.send { background: ${brand}; color: #fff; border: none; border-radius: 8px; padding: 8px 12px; font-size: 13px; cursor: pointer; font-weight: 600; }
        button.send:disabled { opacity: .5; cursor: default; }
        .close { position: absolute; top: 12px; right: 12px; background: none; border: none; color: #fff; font-size: 18px; cursor: pointer; line-height: 1; }
      `;
      this.shadow.appendChild(style);

      this.bubbleEl = document.createElement("button");
      this.bubbleEl.className = "bubble";
      this.bubbleEl.setAttribute("aria-label", "Open chat");
      this.bubbleEl.textContent = "💬";
      this.bubbleEl.onclick = () => this.toggle();
      this.shadow.appendChild(this.bubbleEl);

      this.panelEl = document.createElement("div");
      this.panelEl.className = "panel";
      this.panelEl.style.position = "relative";

      const header = document.createElement("div");
      header.className = "header";
      header.style.position = "relative";
      header.innerHTML = `${escapeHtml(this.config!.title)}<p>${
        this.config!.is_within_business_hours ? escapeHtml(this.config!.greeting_message) : "We're currently offline"
      }</p>`;
      const closeBtn = document.createElement("button");
      closeBtn.className = "close";
      closeBtn.textContent = "✕";
      closeBtn.onclick = () => this.toggle();
      header.appendChild(closeBtn);
      this.panelEl.appendChild(header);

      if (!this.config!.is_within_business_hours && this.config!.offline_message) {
        const offline = document.createElement("div");
        offline.className = "offline";
        offline.textContent = this.config!.offline_message;
        this.panelEl.appendChild(offline);
      }

      this.bodyEl = document.createElement("div");
      this.bodyEl.className = "body";
      this.panelEl.appendChild(this.bodyEl);

      this.formEl = this.buildForm();
      this.panelEl.appendChild(this.formEl);

      this.shadow.appendChild(this.panelEl);
      this.renderMessages();
    }

    private buildForm(): HTMLFormElement {
      const form = document.createElement("form");

      if (!this.session) {
        // pre-chat form: name + email, market-standard table stakes (see plans/)
        const nameInput = document.createElement("input");
        nameInput.placeholder = "Your name";
        nameInput.name = "visitor_name";

        const emailInput = document.createElement("input");
        emailInput.placeholder = "Your email (optional)";
        emailInput.name = "visitor_email";
        emailInput.type = "email";

        form.appendChild(nameInput);
        form.appendChild(emailInput);
      }

      const messageInput = document.createElement("textarea");
      messageInput.placeholder = "Type a message...";
      messageInput.name = "message";
      messageInput.rows = 2;
      form.appendChild(messageInput);

      const sendBtn = document.createElement("button");
      sendBtn.type = "submit";
      sendBtn.className = "send";
      sendBtn.textContent = "Send";
      form.appendChild(sendBtn);

      form.onsubmit = (e) => {
        e.preventDefault();
        void this.handleSubmit(form, sendBtn);
      };

      return form;
    }

    private async handleSubmit(form: HTMLFormElement, sendBtn: HTMLButtonElement) {
      const data = new FormData(form);
      const message = (data.get("message") as string)?.trim();
      if (!message) return;

      sendBtn.disabled = true;
      try {
        if (!this.session) {
          const visitorName = (data.get("visitor_name") as string) || undefined;
          const visitorEmail = (data.get("visitor_email") as string) || undefined;
          const result = await apiFetch(`/public/widget/start`, {
            method: "POST",
            body: JSON.stringify({
              widget_key: widgetKey,
              message,
              visitor_name: visitorName,
              visitor_email: visitorEmail,
              page_url: window.location.href,
            }),
          });
          this.session = { visitor_token: result.visitor_token, conversation_id: result.conversation_id };
          setSession(this.session);
          this.connectSocket();
          // re-render form without the now-unnecessary pre-chat fields
          this.formEl.replaceWith((this.formEl = this.buildForm()));
        } else {
          await apiFetch(`/public/widget/messages`, {
            method: "POST",
            headers: { Authorization: `Bearer ${this.session.visitor_token}` },
            body: JSON.stringify({ content: message }),
          });
        }
        this.messages.push({ direction: "outbound", content: message });
        this.renderMessages();
        form.reset();
      } catch (e) {
        console.error("[SmartSales Widget] send failed", e);
      } finally {
        sendBtn.disabled = false;
      }
    }

    private renderMessages() {
      this.bodyEl.innerHTML = "";
      for (const m of this.messages) {
        const el = document.createElement("div");
        el.className = `msg ${m.direction}`;
        el.textContent = m.content;
        this.bodyEl.appendChild(el);
      }
      this.bodyEl.scrollTop = this.bodyEl.scrollHeight;
    }

    private connectSocket() {
      if (!this.session || this.ws) return;
      const socket = new WebSocket(`${wsUrl}/public/widget/ws?token=${encodeURIComponent(this.session.visitor_token)}`);
      this.ws = socket;

      socket.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data);
          if (data.type === "message") {
            this.messages.push({ direction: "inbound", content: data.content });
            this.renderMessages();
          }
        } catch {
          /* ignore malformed frames */
        }
      };

      socket.onopen = () => {
        this.pingTimer = window.setInterval(() => {
          if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: "ping" }));
        }, PING_INTERVAL_MS);
      };

      socket.onclose = () => {
        if (this.pingTimer) window.clearInterval(this.pingTimer);
        this.ws = null;
        // simple reconnect - a visitor's tab can stay open far longer than any single WS connection lives
        setTimeout(() => this.connectSocket(), 5000);
      };
    }

    private toggle() {
      this.isOpen = !this.isOpen;
      this.panelEl.classList.toggle("open", this.isOpen);
    }
  }

  function escapeHtml(s: string): string {
    const div = document.createElement("div");
    div.textContent = s;
    return div.innerHTML;
  }

  function boot() {
    new SmartSalesWidget().init();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
