/**
 * SmartSales Web Widget - embeddable chat bubble.
 *
 * Deliberately vanilla TypeScript (no React/Preact) rendered into a Shadow
 * DOM: this script runs on a THIRD-PARTY tenant website, not inside
 * supercontact-web itself, so it must not bloat the host page's bundle or
 * collide with whatever framework/CSS that page already uses. See plans/
 * for the full architecture rationale.
 *
 * Reads its own <script data-widget-key="..." data-api-url="..."> tag via
 * document.currentScript - both attributes are generated by the tenant's
 * Settings > Web Widget page (WebWidgetEmbedGuide.tsx) at copy time, so
 * this bundle itself never hardcodes an environment.
 */

interface WidgetConfig {
  title: string;
  greeting_message: string;
  brand_color: string;
  is_widget_enabled: boolean;
  is_within_business_hours: boolean;
  offline_message?: string | null;
  // i18n (POLISH sprint): the public config endpoint does NOT currently
  // return these, so today they're always undefined and the widget falls
  // back to the data-locale attribute (default "id"). Kept optional so that
  // IF the backend ever adds a `locale`/`strings` field to get_public_config
  // it's picked up with zero further frontend change - see resolveStrings().
  locale?: "id" | "en" | string | null;
  strings?: Partial<WidgetStrings> | null;
}

// All visitor-facing chrome strings. Everything the widget renders in the
// UI flows through one of these keys so the bundle can ship more than one
// language pack without touching the backend.
interface WidgetStrings {
  offline: string;
  disconnected: string;
  yourName: string;
  yourEmail: string;
  typeMessage: string;
  send: string;
  openChat: string;
  closeChat: string;
  failedRetry: string;
  newMessage: string;
  downloadAttachment: string;
  attachment: string;
}

const STRINGS_EN: WidgetStrings = {
  offline: "We're currently offline",
  disconnected: "Disconnected — refresh to reconnect",
  yourName: "Your name",
  yourEmail: "Your email (optional)",
  typeMessage: "Type a message...",
  send: "Send",
  openChat: "Open chat",
  closeChat: "Close chat",
  failedRetry: "Failed — tap to retry",
  newMessage: "New message",
  downloadAttachment: "Download attachment",
  attachment: "attachment",
};

const STRINGS_ID: WidgetStrings = {
  offline: "Kami sedang offline",
  disconnected: "Koneksi terputus — muat ulang untuk menyambung kembali",
  yourName: "Nama Anda",
  yourEmail: "Email Anda (opsional)",
  typeMessage: "Ketik pesan...",
  send: "Kirim",
  openChat: "Buka obrolan",
  closeChat: "Tutup obrolan",
  failedRetry: "Gagal — ketuk untuk mencoba lagi",
  newMessage: "Pesan baru",
  downloadAttachment: "Unduh lampiran",
  attachment: "lampiran",
};

// Base pack selected by locale (default Indonesian - the product's tenants
// are Indonesian), then merged with any per-string overrides (only ever
// present if the backend later supplies config.strings).
function resolveStrings(
  locale: string | null | undefined,
  overrides?: Partial<WidgetStrings> | null,
): WidgetStrings {
  const base = locale === "en" ? STRINGS_EN : STRINGS_ID;
  const merged: WidgetStrings = { ...base };
  if (overrides) {
    for (const k in overrides) {
      const v = (overrides as Record<string, unknown>)[k];
      if (typeof v === "string" && v.trim()) (merged as unknown as Record<string, string>)[k] = v;
    }
  }
  return merged;
}

interface StoredSession {
  visitor_token: string;
  conversation_id: string;
}

interface WidgetAttachment {
  filename?: string | null;
  content_type?: string | null;
  media_url: string;
  is_inline?: boolean;
}

interface WidgetMessage {
  id?: string;
  direction: "inbound" | "outbound";
  content: string;
  sent_at?: string;
  media_url?: string | null;
  attachments?: WidgetAttachment[];
  // Client-only bookkeeping (never sent to the server):
  client_message_id?: string; // idempotency key so a retry can't double-post
  status?: "sending" | "sent" | "failed";
  startCtx?: { visitor_name?: string; visitor_email?: string };
}

// Server-shaped message as returned by GET /public/widget/conversation and
// the WS "message" frame. NOTE the direction inversion vs the widget UI:
// the backend is company-centric (visitor = "inbound", agent = "outbound"),
// but the visitor-facing bubble is visitor-centric (their own message =
// "outbound"/right, an agent reply = "inbound"/left). fromServer() flips it.
interface ServerMessage {
  id?: string;
  direction?: string;
  content?: string;
  sent_at?: string;
  media_url?: string | null;
  attachments?: WidgetAttachment[] | null;
}

(function () {
  const currentScript = document.currentScript as HTMLScriptElement | null;
  if (!currentScript) return;

  const widgetKey = currentScript.getAttribute("data-widget-key");
  const apiUrl = (currentScript.getAttribute("data-api-url") || "").replace(/\/$/, "");
  // Optional locale override on the embed <script data-locale="en"> tag.
  // Absent => "id" (default, tenants are Indonesian). Zero backend change.
  const localeAttr = (currentScript.getAttribute("data-locale") || "").trim().toLowerCase();
  // Optional absolute WebSocket base on the embed <script data-ws-url="wss://..."> tag.
  // Needed when data-api-url is a relative/same-origin path (e.g. a "/api/proxy"
  // that only forwards REST, not WS upgrades): the derived ws base below would be
  // an invalid relative WebSocket URL. When absent, derive ws base from apiUrl as
  // before (correct for the standard absolute-URL tenant embed).
  const wsUrlAttr = (currentScript.getAttribute("data-ws-url") || "").replace(/\/$/, "");
  if (!widgetKey || !apiUrl) {
    console.error("[SmartSales Widget] missing data-widget-key or data-api-url");
    return;
  }

  const wsUrl = wsUrlAttr || apiUrl.replace(/^http/, "ws");
  const storageKey = `smartsales_widget_session_${widgetKey}`;
  const PING_INTERVAL_MS = 2 * 60 * 1000; // well under the server's 5-minute idle timeout
  // Reconnect backoff (item 2): exponential base 1s, cap 30s, full jitter.
  const RECONNECT_BASE_MS = 1000;
  const RECONNECT_CAP_MS = 30000;
  const WS_POLICY_CLOSE = 1008; // auth/origin/too-many rejection - do NOT loop

  function getSession(): StoredSession | null {
    try {
      const raw = localStorage.getItem(storageKey);
      return raw ? (JSON.parse(raw) as StoredSession) : null;
    } catch {
      return null;
    }
  }

  function setSession(session: StoredSession) {
    try {
      localStorage.setItem(storageKey, JSON.stringify(session));
    } catch {
      /* localStorage unavailable (private mode, etc) - session just won't persist across reloads */
    }
  }

  // Item 4 (expired-token cleanup): purge the persisted token so a reload
  // doesn't keep replaying an expired/invalid token. Called on a hard 401
  // from the REST API (unambiguous token-expired), NOT on a WS 1008 close -
  // 1008 also covers too-many-connections/origin, where the token is fine.
  function removeSession() {
    try {
      localStorage.removeItem(storageKey);
    } catch {
      /* localStorage unavailable - nothing persisted to remove */
    }
  }

  function genClientMessageId(): string {
    try {
      const c = (globalThis as { crypto?: Crypto }).crypto;
      if (c && typeof c.randomUUID === "function") return c.randomUUID();
    } catch {
      /* fall through to the non-crypto fallback below */
    }
    return `cmid-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 12)}`;
  }

  function prefersReducedMotion(): boolean {
    try {
      return !!window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    } catch {
      return false;
    }
  }

  // Flip company-centric server direction to visitor-centric UI direction.
  function fromServer(m: ServerMessage): WidgetMessage {
    return {
      id: m.id,
      direction: m.direction === "outbound" ? "inbound" : "outbound",
      content: m.content || "",
      sent_at: m.sent_at,
      media_url: m.media_url ?? null,
      attachments: m.attachments || [],
      status: "sent",
    };
  }

  async function apiFetch(path: string, options: RequestInit = {}) {
    const res = await fetch(`${apiUrl}${path}`, {
      ...options,
      headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) {
      const err = new Error(json?.error?.message || json?.message || "Request failed") as Error & {
        status?: number;
      };
      err.status = res.status; // lets callers detect a 401 for token cleanup (item 4)
      throw err;
    }
    return json?.data ?? json;
  }

  class SmartSalesWidget {
    private root: HTMLDivElement;
    private shadow: ShadowRoot;
    private config: WidgetConfig | null = null;
    private strings: WidgetStrings = resolveStrings(localeAttr);
    private session: StoredSession | null = getSession();
    private ws: WebSocket | null = null;
    private pingTimer: number | null = null;
    private reconnectTimer: number | null = null;
    private reconnectAttempts = 0;
    private stoppedReconnect = false;
    private messages: WidgetMessage[] = [];
    // ids of messages already incorporated from server/WS - dedupes a WS
    // redelivery/echo and a history replay of an already-shown message.
    private serverIds = new Set<string>();
    private isOpen = false;
    private unreadCount = 0;
    private titleFlashTimer: number | null = null;
    private originalTitle = "";

    private bubbleEl!: HTMLButtonElement;
    private badgeEl!: HTMLSpanElement;
    private panelEl!: HTMLDivElement;
    private bodyEl!: HTMLDivElement;
    private statusEl!: HTMLDivElement;
    private formEl!: HTMLFormElement;

    constructor() {
      this.root = document.createElement("div");
      this.root.id = "smartsales-widget-root";
      document.body.appendChild(this.root);
      this.shadow = this.root.attachShadow({ mode: "open" });
    }

    async init() {
      try {
        this.config = await apiFetch(`/public/widget/config/${widgetKey}`);
      } catch (e) {
        console.error("[SmartSales Widget] failed to load config", e);
        return;
      }
      if (!this.config || !this.config.is_widget_enabled) return;

      // Precedence: backend config.locale (future) > data-locale attr > "id".
      this.strings = resolveStrings(this.config.locale || localeAttr, this.config.strings);

      this.render();

      // Stop the title flash / (unread stays until the panel is opened) when
      // the visitor returns to this tab.
      window.addEventListener("focus", () => this.stopTitleFlash());

      if (this.session) {
        // Load history immediately, then connect. connectSocket's onopen
        // resyncs again to catch anything that arrived during the outage.
        await this.resyncHistory();
        this.connectSocket();
      }
    }

    private render() {
      const brand = this.config!.brand_color || "#5479EE";
      const style = document.createElement("style");
      style.textContent = `
        :host { all: initial; }
        * { box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
        .bubble {
          position: fixed; bottom: 20px; right: 20px; width: 56px; height: 56px;
          border-radius: 50%; background: ${brand}; color: #fff; border: none;
          cursor: pointer; box-shadow: 0 4px 14px rgba(0,0,0,.2); z-index: 2147483000;
          display: flex; align-items: center; justify-content: center; font-size: 26px;
        }
        .badge {
          position: absolute; top: -4px; right: -4px; min-width: 20px; height: 20px;
          padding: 0 5px; border-radius: 10px; background: #EF4444; color: #fff;
          font-size: 11px; font-weight: 700; line-height: 20px; text-align: center;
          box-shadow: 0 0 0 2px #fff; display: none;
        }
        .badge.show { display: block; }
        .panel {
          position: fixed; bottom: 88px; right: 20px; width: 340px; max-width: calc(100vw - 40px);
          height: 480px; max-height: calc(100vh - 120px); background: #fff; border-radius: 12px;
          box-shadow: 0 8px 30px rgba(0,0,0,.2); display: none; flex-direction: column; overflow: hidden;
          z-index: 2147483000;
        }
        .panel.open { display: flex; }
        .header { background: ${brand}; color: #fff; padding: 14px 16px; font-weight: 600; font-size: 15px; }
        .header p { margin: 2px 0 0; font-size: 12px; font-weight: 400; opacity: .85; }
        .status { display: none; padding: 6px 12px; background: #F3F4F6; color: #6B7280; font-size: 11px; text-align: center; }
        .status.show { display: block; }
        .body { flex: 1; overflow-y: auto; padding: 12px; display: flex; flex-direction: column; gap: 8px; background: #F9FAFB; }
        .msg { max-width: 80%; padding: 8px 12px; border-radius: 10px; font-size: 13px; line-height: 1.4; white-space: pre-wrap; word-break: break-word; }
        .msg.inbound { align-self: flex-start; background: #fff; border: 1px solid #E5E7EB; color: #111827; }
        .msg.outbound { align-self: flex-end; background: ${brand}; color: #fff; }
        .msg.failed { opacity: .85; }
        .msg .att-image { display: block; margin-top: 6px; }
        .msg .att-image img { max-width: 100%; border-radius: 8px; display: block; }
        .msg .att-file { display: inline-block; margin-top: 6px; font-size: 12px; text-decoration: underline; color: inherit; word-break: break-all; }
        .retry { display: block; margin-top: 6px; background: none; border: none; padding: 0; cursor: pointer; font-size: 11px; font-weight: 600; color: #FCA5A5; text-align: left; }
        .msg.inbound .retry { color: #DC2626; }
        .offline { padding: 10px 12px; background: #FEF3C7; color: #92400E; font-size: 12px; }
        form { display: flex; flex-direction: column; gap: 8px; padding: 12px; border-top: 1px solid #E5E7EB; }
        /* 16px (not 13px) so iOS Safari doesn't zoom the page on focus (item 2 a11y). */
        input, textarea { border: 1px solid #E5E7EB; border-radius: 8px; padding: 8px 10px; font-size: 16px; outline: none; }
        input:focus, textarea:focus { border-color: ${brand}; }
        button.send { background: ${brand}; color: #fff; border: none; border-radius: 8px; padding: 8px 12px; font-size: 13px; cursor: pointer; font-weight: 600; }
        button.send:disabled { opacity: .5; cursor: default; }
        .close { position: absolute; top: 12px; right: 12px; background: none; border: none; color: #fff; font-size: 18px; cursor: pointer; line-height: 1; }
      `;
      this.shadow.appendChild(style);

      this.bubbleEl = document.createElement("button");
      this.bubbleEl.className = "bubble";
      this.bubbleEl.setAttribute("aria-label", this.strings.openChat);
      this.bubbleEl.textContent = "💬";
      this.bubbleEl.onclick = () => this.toggle();
      this.badgeEl = document.createElement("span");
      this.badgeEl.className = "badge";
      this.badgeEl.setAttribute("aria-hidden", "true");
      this.bubbleEl.appendChild(this.badgeEl);
      this.shadow.appendChild(this.bubbleEl);

      this.panelEl = document.createElement("div");
      this.panelEl.className = "panel";
      this.panelEl.style.position = "relative";

      const header = document.createElement("div");
      header.className = "header";
      header.style.position = "relative";
      header.innerHTML = `${escapeHtml(this.config!.title)}<p>${
        this.config!.is_within_business_hours ? escapeHtml(this.config!.greeting_message) : escapeHtml(this.strings.offline)
      }</p>`;
      const closeBtn = document.createElement("button");
      closeBtn.className = "close";
      closeBtn.setAttribute("aria-label", this.strings.closeChat);
      closeBtn.textContent = "✕";
      closeBtn.onclick = () => this.toggle();
      header.appendChild(closeBtn);
      this.panelEl.appendChild(header);

      // Subtle connection-state line (item 2): only shown once we've given up
      // reconnecting after an auth/policy close, so the visitor knows the
      // live channel is down rather than silently swallowing agent replies.
      this.statusEl = document.createElement("div");
      this.statusEl.className = "status";
      this.statusEl.setAttribute("role", "status");
      this.statusEl.textContent = this.strings.disconnected;
      this.panelEl.appendChild(this.statusEl);

      if (!this.config!.is_within_business_hours && this.config!.offline_message) {
        const offline = document.createElement("div");
        offline.className = "offline";
        offline.textContent = this.config!.offline_message;
        this.panelEl.appendChild(offline);
      }

      this.bodyEl = document.createElement("div");
      this.bodyEl.className = "body";
      // a11y (item 2): announce agent replies to screen readers as they arrive.
      this.bodyEl.setAttribute("role", "log");
      this.bodyEl.setAttribute("aria-live", "polite");
      this.bodyEl.setAttribute("aria-atomic", "false");
      this.panelEl.appendChild(this.bodyEl);

      this.formEl = this.buildForm();
      this.panelEl.appendChild(this.formEl);

      this.shadow.appendChild(this.panelEl);
      this.renderMessages();
    }

    private buildForm(): HTMLFormElement {
      const form = document.createElement("form");

      if (!this.session) {
        // pre-chat form: name + email, market-standard table stakes (see plans/)
        const nameInput = document.createElement("input");
        nameInput.placeholder = this.strings.yourName;
        nameInput.setAttribute("aria-label", this.strings.yourName);
        nameInput.name = "visitor_name";

        const emailInput = document.createElement("input");
        emailInput.placeholder = this.strings.yourEmail;
        emailInput.setAttribute("aria-label", this.strings.yourEmail);
        emailInput.name = "visitor_email";
        emailInput.type = "email";

        form.appendChild(nameInput);
        form.appendChild(emailInput);
      }

      const messageInput = document.createElement("textarea");
      messageInput.placeholder = this.strings.typeMessage;
      messageInput.setAttribute("aria-label", this.strings.typeMessage);
      messageInput.name = "message";
      messageInput.rows = 2;
      // Enter sends, Shift+Enter inserts a newline (keyboard operability, item 2).
      messageInput.addEventListener("keydown", (e) => {
        if (e.key === "Enter" && !e.shiftKey) {
          e.preventDefault();
          if (typeof form.requestSubmit === "function") form.requestSubmit();
          else void this.handleSubmit(form, sendBtn);
        }
      });
      form.appendChild(messageInput);

      const sendBtn = document.createElement("button");
      sendBtn.type = "submit";
      sendBtn.className = "send";
      sendBtn.setAttribute("aria-label", this.strings.send);
      sendBtn.textContent = this.strings.send;
      form.appendChild(sendBtn);

      form.onsubmit = (e) => {
        e.preventDefault();
        void this.handleSubmit(form, sendBtn);
      };

      return form;
    }

    private async handleSubmit(form: HTMLFormElement, sendBtn: HTMLButtonElement) {
      const data = new FormData(form);
      const message = (data.get("message") as string)?.trim();
      if (!message) return;

      const startCtx = !this.session
        ? {
            visitor_name: (data.get("visitor_name") as string) || undefined,
            visitor_email: (data.get("visitor_email") as string) || undefined,
          }
        : undefined;

      // Optimistic render with a fresh idempotency key. A retry re-POSTs the
      // SAME client_message_id so the backend dedup makes it safe (item 4).
      const msg: WidgetMessage = {
        direction: "outbound",
        content: message,
        client_message_id: genClientMessageId(),
        status: "sending",
        startCtx,
      };
      this.messages.push(msg);
      this.renderMessages();
      form.reset();

      await this.attemptSend(msg, sendBtn);
    }

    private async attemptSend(msg: WidgetMessage, sendBtn?: HTMLButtonElement) {
      msg.status = "sending";
      this.renderMessages();
      if (sendBtn) sendBtn.disabled = true;
      try {
        if (!this.session) {
          const result = await apiFetch(`/public/widget/start`, {
            method: "POST",
            body: JSON.stringify({
              widget_key: widgetKey,
              message: msg.content,
              visitor_name: msg.startCtx?.visitor_name,
              visitor_email: msg.startCtx?.visitor_email,
              page_url: window.location.href,
            }),
          });
          this.session = { visitor_token: result.visitor_token, conversation_id: result.conversation_id };
          setSession(this.session);
          this.connectSocket();
          // re-render form without the now-unnecessary pre-chat fields
          this.formEl.replaceWith((this.formEl = this.buildForm()));
        } else {
          await apiFetch(`/public/widget/messages`, {
            method: "POST",
            headers: { Authorization: `Bearer ${this.session.visitor_token}` },
            body: JSON.stringify({ content: msg.content, client_message_id: msg.client_message_id }),
          });
        }
        msg.status = "sent";
      } catch (e) {
        console.error("[SmartSales Widget] send failed", e);
        msg.status = "failed";
        // Expired/revoked token on an authenticated send: purge it (item 4).
        if ((e as { status?: number })?.status === 401) this.clearSession();
      } finally {
        if (sendBtn) sendBtn.disabled = false;
        this.renderMessages();
      }
    }

    private buildAttachmentEl(att: WidgetAttachment): HTMLElement | null {
      const url = (att.media_url || "").trim();
      if (!url) return null;
      const ct = (att.content_type || "").toLowerCase();
      const isImage = ct.startsWith("image/") || /\.(png|jpe?g|gif|webp|bmp|svg)(\?|$)/i.test(url);

      const link = document.createElement("a");
      link.href = url;
      link.target = "_blank";
      link.rel = "noopener noreferrer";

      if (isImage) {
        link.className = "att-image";
        const img = document.createElement("img");
        img.src = url;
        img.alt = att.filename || this.strings.attachment;
        img.loading = "lazy";
        link.appendChild(img);
      } else {
        link.className = "att-file";
        link.textContent = `📎 ${att.filename || this.strings.downloadAttachment}`;
      }
      return link;
    }

    private renderMessages() {
      this.bodyEl.innerHTML = "";
      for (const m of this.messages) {
        const el = document.createElement("div");
        el.className = `msg ${m.direction}${m.status === "failed" ? " failed" : ""}`;

        if (m.content) {
          const text = document.createElement("div");
          text.className = "msg-text";
          text.textContent = m.content;
          el.appendChild(text);
        }

        const media =
          m.attachments && m.attachments.length
            ? m.attachments
            : m.media_url
              ? [{ media_url: m.media_url } as WidgetAttachment]
              : [];
        for (const att of media) {
          const attEl = this.buildAttachmentEl(att);
          if (attEl) el.appendChild(attEl);
        }

        if (m.direction === "outbound" && m.status === "failed") {
          const retry = document.createElement("button");
          retry.type = "button";
          retry.className = "retry";
          retry.textContent = this.strings.failedRetry;
          retry.onclick = () => void this.attemptSend(m);
          el.appendChild(retry);
        }

        this.bodyEl.appendChild(el);
      }
      this.bodyEl.scrollTop = this.bodyEl.scrollHeight;
    }

    // Re-fetch full history and reconcile (item 3). Server state is
    // authoritative for everything persisted; we keep only local outbound
    // messages that are still in-flight or failed (not yet on the server),
    // so agent messages that arrived during an outage show up without
    // duplicating anything already rendered.
    private async resyncHistory() {
      if (!this.session) return;
      try {
        const conv = await apiFetch(`/public/widget/conversation`, {
          headers: { Authorization: `Bearer ${this.session.visitor_token}` },
        });
        const serverMsgs: WidgetMessage[] = (conv.messages || []).map(fromServer);
        const pendingLocal = this.messages.filter(
          (m) => m.direction === "outbound" && (m.status === "sending" || m.status === "failed"),
        );
        this.serverIds = new Set(
          serverMsgs.filter((m): m is WidgetMessage & { id: string } => !!m.id).map((m) => m.id),
        );
        this.messages = [...serverMsgs, ...pendingLocal];
        this.renderMessages();
      } catch (e) {
        // A 401 means the visitor token expired/was revoked: purge it so a
        // reload starts a fresh pre-chat rather than replaying a dead token
        // (item 4). Any other failure is non-fatal - keep what's rendered.
        if ((e as { status?: number })?.status === 401) this.clearSession();
      }
    }

    // Item 4: drop the persisted + in-memory token and reset to the pre-chat
    // state so the visitor can start over cleanly.
    private clearSession() {
      removeSession();
      this.session = null;
      this.serverIds = new Set();
      this.stoppedReconnect = true;
      if (this.formEl) this.formEl.replaceWith((this.formEl = this.buildForm()));
    }

    private connectSocket() {
      if (!this.session || this.ws) return;
      const socket = new WebSocket(`${wsUrl}/public/widget/ws?token=${encodeURIComponent(this.session.visitor_token)}`);
      this.ws = socket;

      socket.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data) as ServerMessage & { type?: string };
          if (data.type === "message") {
            // Dedupe redelivery/echo by id (item 3).
            if (data.id && this.serverIds.has(data.id)) return;
            if (data.id) this.serverIds.add(data.id);
            const msg = fromServer(data);
            this.messages.push(msg);
            this.renderMessages();
            // Unread badge (item 6): only agent (inbound) frames, only while closed.
            if (!this.isOpen && msg.direction === "inbound") this.incrementUnread();
          }
        } catch {
          /* ignore malformed frames */
        }
      };

      socket.onopen = () => {
        this.reconnectAttempts = 0; // reset backoff on a successful open
        this.setDisconnected(false);
        this.pingTimer = window.setInterval(() => {
          if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: "ping" }));
        }, PING_INTERVAL_MS);
        // Catch anything missed while the socket was down (item 3).
        void this.resyncHistory();
      };

      socket.onclose = (event) => {
        if (this.pingTimer) window.clearInterval(this.pingTimer);
        this.pingTimer = null;
        this.ws = null;
        // Auth/origin/too-many-connections close: reconnecting can't fix it,
        // so stop looping and show a subtle disconnected state (item 2).
        if (event.code === WS_POLICY_CLOSE) {
          this.stoppedReconnect = true;
          this.setDisconnected(true);
          return;
        }
        this.scheduleReconnect();
      };
    }

    private scheduleReconnect() {
      if (this.stoppedReconnect || this.reconnectTimer) return;
      // Exponential backoff with FULL jitter: delay in [0, min(cap, base*2^n)).
      const ceiling = Math.min(RECONNECT_CAP_MS, RECONNECT_BASE_MS * Math.pow(2, this.reconnectAttempts));
      const delay = Math.random() * ceiling;
      this.reconnectAttempts++;
      this.reconnectTimer = window.setTimeout(() => {
        this.reconnectTimer = null;
        this.connectSocket();
      }, delay);
    }

    private setDisconnected(on: boolean) {
      this.statusEl.classList.toggle("show", on);
    }

    private incrementUnread() {
      this.unreadCount++;
      this.badgeEl.textContent = this.unreadCount > 99 ? "99+" : String(this.unreadCount);
      this.badgeEl.classList.add("show");
      this.startTitleFlash();
    }

    private clearUnread() {
      this.unreadCount = 0;
      this.badgeEl.classList.remove("show");
      this.badgeEl.textContent = "";
      this.stopTitleFlash();
    }

    // Optional, tasteful title flash (item 6). Suppressed under
    // prefers-reduced-motion, and it ALWAYS restores the host page's original
    // <title> - this runs on arbitrary tenant sites, so it must leave no trace.
    private startTitleFlash() {
      if (prefersReducedMotion() || this.titleFlashTimer || document.hasFocus()) return;
      this.originalTitle = document.title;
      let alt = false;
      this.titleFlashTimer = window.setInterval(() => {
        document.title = alt ? this.originalTitle : `💬 ${this.strings.newMessage}`;
        alt = !alt;
      }, 1200);
    }

    private stopTitleFlash() {
      if (this.titleFlashTimer) {
        window.clearInterval(this.titleFlashTimer);
        this.titleFlashTimer = null;
        if (this.originalTitle) document.title = this.originalTitle;
      }
    }

    private toggle() {
      this.isOpen = !this.isOpen;
      this.panelEl.classList.toggle("open", this.isOpen);
      if (this.isOpen) {
        this.clearUnread();
        // a11y (item 2): move focus into the composer when the panel opens.
        const input = this.formEl?.querySelector('textarea[name="message"]') as HTMLTextAreaElement | null;
        if (input) window.setTimeout(() => input.focus(), 0);
      }
    }
  }

  function escapeHtml(s: string): string {
    const div = document.createElement("div");
    div.textContent = s;
    return div.innerHTML;
  }

  function boot() {
    new SmartSalesWidget().init();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
