import { MRT_Localization } from 'material-react-table';

export const MRT_Localization_ID: MRT_Localization = {
  language: 'id',
  actions: 'Aksi',
  and: 'dan',
  cancel: 'Batal',
  changeFilterMode: 'Ubah mode filter',
  changeSearchMode: 'Ubah mode pencarian',
  clearFilter: 'Hapus filter',
  clearSearch: 'Hapus pencarian',
  clearSelection: 'Bersihkan pilihan',
  clearSort: 'Hapus pengurutan',
  clickToCopy: 'Klik untuk menyalin',
  collapse: 'Ciutkan',
  collapseAll: 'Ciutkan semua',
  columnActions: 'Aksi kolom',
  copiedToClipboard: 'Tersalin ke clipboard',
  copy: 'Salin',
  dropToGroupBy: 'Lepas untuk grup berdasar',
  edit: 'Ubah',
  expand: 'Perluas',
  expandAll: 'Perluas semua',
  filterArrIncludes: 'Termasuk salah satu',
  filterArrIncludesAll: 'Termasuk semua',
  filterArrIncludesSome: 'Termasuk beberapa',
  filterBetween: 'Di antara',
  filterBetweenInclusive: 'Di antara (inklusif)',
  filterByColumn: 'Filter berdasar {column}',
  filterContains: 'Mengandung',
  filterEmpty: 'Kosong',
  filterEndsWith: 'Diakhiri dengan',
  filterEquals: 'Sama dengan',
  filterEqualsString: 'Sama persis',
  filterFuzzy: 'Kira-kira',
  filterGreaterThan: 'Lebih dari',
  filterGreaterThanOrEqualTo: 'Lebih dari atau sama dengan',
  filterInNumberRange: 'Dalam rentang angka',
  filterIncludesString: 'Mengandung teks',
  filterIncludesStringSensitive: 'Mengandung teks (case-sensitive)',
  filterLessThan: 'Kurang dari',
  filterLessThanOrEqualTo: 'Kurang dari atau sama dengan',
  filterMode: 'Mode filter: {filterType}',
  filterNotEmpty: 'Tidak kosong',
  filterNotEquals: 'Tidak sama dengan',
  filterStartsWith: 'Dimulai dengan',
  filterWeakEquals: 'Hampir sama',
  filteringByColumn: 'Memfilter berdasar {column} - {filterType} {filterValue}',
  goToFirstPage: 'Ke halaman pertama',
  goToLastPage: 'Ke halaman terakhir',
  goToNextPage: 'Ke halaman berikutnya',
  goToPreviousPage: 'Ke halaman sebelumnya',
  grab: 'Geser',
  groupByColumn: 'Kelompokkan berdasar {column}',
  groupedBy: 'Dikelompokkan berdasar',
  hideAll: 'Sembunyikan semua',
  hideColumn: 'Sembunyikan kolom {column}',
  max: 'Maks',
  min: 'Min',
  move: 'Pindah',
  noRecordsToDisplay: 'Tidak ada data untuk ditampilkan',
  noResultsFound: 'Tidak ada hasil yang cocok',
  of: 'dari',
  or: 'atau',
  pin: 'Sematkan',
  pinToLeft: 'Sematkan ke kiri',
  pinToRight: 'Sematkan ke kanan',
  resetColumnSize: 'Reset ukuran kolom',
  resetOrder: 'Reset urutan',
  rowActions: 'Aksi baris',
  rowNumber: 'No.',
  rowNumbers: 'Nomor baris',
  rowsPerPage: 'Baris per halaman',
  save: 'Simpan',
  search: 'Cari...',
  select: 'Pilih',
  selectedCountOfRowCountRowsSelected: '{selectedCount} dari {rowCount} baris dipilih',
  showAll: 'Tampilkan semua',
  showAllColumns: 'Tampilkan semua kolom',
  showHideColumns: 'Tampilkan/Sembunyikan kolom',
  showHideFilters: 'Tampilkan/Sembunyikan filter',
  showHideSearch: 'Tampilkan/Sembunyikan pencarian',
  sortByColumnAsc: 'Urutkan {column} A ke Z',
  sortByColumnDesc: 'Urutkan {column} Z ke A',
  sortedByColumnAsc: 'Diurutkan berdasar {column} naik',
  sortedByColumnDesc: 'Diurutkan berdasar {column} turun',
  thenBy: ', lalu berdasar',
  toggleDensity: 'Ubah kepadatan tampilan',
  toggleFullScreen: 'Layar penuh',
  toggleSelectAll: 'Pilih semua',
  toggleSelectRow: 'Pilih baris ini',
  toggleVisibility: 'Ubah visibilitas',
  ungroupByColumn: 'Batalkan grup berdasar {column}',
  unpin: 'Lepas sematan',
  unpinAll: 'Lepas semua sematan',
};
